### ISSUE TITLE
nginx vhost try_files return 404

### ISSUE THREAD

**Issue by itaied246** [bitnami/bitnami-docker-nginx#104]
ui_vhost.conf

```
server {
  listen 8080;
  root /app;
  index index.html;

  location / {
    try_files $uri$args $uri$args/ $uri $uri/ /index.html =404;
  }
}
```
Dockerfile

```
FROM bitnami/nginx
COPY dist /app
COPY ui_vhost.conf /opt/bitnami/nginx/conf/vhosts/ui_vhost.conf:ro
```

My app is based on angularjs.
Loading the website works for the first time when I navigate to another route (for example /home).
When I hit refesh, I receive 404 and the logs are:

open() "/opt/bitnami/nginx/html/home" failed (2: no such file or directory) ...
Why doesn't nginx return the index.html?
Why it seems to ignore the try_files directive?

**Comment by marcosbc** [comment]
Hi @itaied246, you are copying your `ui_vhost.conf` file wrong, you should be doing this:

    COPY ui_vhost.conf /opt/bitnami/nginx/conf/vhosts/ui_vhost.conf:ro

Note that we removed the ":ro". The reason is because you only need to add ":ro" when mounting as a volume in "docker-compose.yml", which is not your case:

    volumes:
      - /path/to/my_vhost.conf:/opt/bitnami/nginx/conf/vhosts/my_vhost.conf:ro

I hope it works!
