### ISSUE TITLE
Question regarding /bitnami and /opt/bitnami

### ISSUE THREAD

**Issue by crcjwice123** [bitnami/bitnami-docker-nginx#111]
**Description**

Just wondering why /bitnami/nginx/conf/vhosts/ and /opt/bitnami/nginx/conf/vhosts folder contains exactly the same file yourapp.conf. Below is the volume in docker-compose.yaml.
```
    volumes:
      - ./vhost.conf:/bitnami/nginx/conf/vhosts/yourapp.conf
```

**Comment by andresbono** [comment]
Hi @crcjwice123, if you check the container logs you should find the following messages:

```
INFO  ==> Initializing NGINX...
WARN  ==> Custom vhosts config files were found in a legacy directory: /bitnami/nginx/conf/vhosts
WARN  ==>   Please use /opt/bitnami/nginx/conf/vhosts instead
```

The container detects the files mounted in `/bitnami/nginx/conf/vhosts/` and copies them to the right place. You can check the logic [here](https://github.com/bitnami/bitnami-docker-nginx/blob/master/1.14/debian-9/rootfs/libnginx.sh#L153-L158) for more details.

Hope this information is useful for you!
