### ISSUE TITLE
Reverse proxy examples

### ISSUE THREAD

**Issue by jameswmcnab** [bitnami/bitnami-docker-nginx#113]
I'm looking at using this image as a https reverse proxy in front of [bitnami-docker-redmine](https://github.com/bitnami/bitnami-docker-redmine).

The readme for this project states (under [Reverse proxy to other containers
](https://github.com/bitnami/bitnami-docker-nginx/blob/master/README.md#reverse-proxy-to-other-containers)):

>  Bitnami provides example virtual hosts for all of our runtime containers in /opt/bitnami/nginx/conf/vhosts/.

However the there is no `/opt/bitnami/nginx/conf/vhosts/` directory within the image:

```bash
$ docker run -it --rm bitnami/nginx /bin/bash

Welcome to the Bitnami nginx container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-nginx
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-nginx/issues
Send us your feedback at containers@bitnami.com


I have no name!@0ba1702defd3:/opt/bitnami/nginx/html$ ls /opt/bitnami/nginx/
conf  html  licenses  logs  sbin
```

Am I missing something obvious here?

**Comment by andresbono** [comment]
Hi @jameswmcnab, we are the ones that missed an update in the README, sorry!

The README refers to these files: [bitnami-docker-nginx/vhosts](https://github.com/bitnami/bitnami-docker-nginx/tree/e6eaa602120e1e4ca807f9561510f592744a89a0/vhosts), but those are no longer available in the repository.

In the meantime we update the README with an example, maybe this other issue can be useful for you:

- https://github.com/bitnami/bitnami-docker-odoo/issues/55#issuecomment-473827764

In your case you will need something similar but you will be proxy-passing to `http://redmine:3000` in the nginx virtual host configuration file:

```
    location / {
        proxy_pass http://odoo:8069;
```

**Comment by jameswmcnab** [comment]
Hi @andresbono and thank you!

Thanks for the example link, I had this working I was just going to use the example file as my basis if it was available as that seemed to be the most 'recommended' way from reading the README.

Thanks again!

**Comment by andresbono** [comment]
Hi @jameswmcnab we updated the README. Thanks for letting us know!
