### ISSUE TITLE
Provide ngx_http_sub_module compiled with Nginx

### ISSUE THREAD

**Issue by ropable** [bitnami/bitnami-docker-nginx#119]
**Description**

I am trying to use the Bitnami Nginx Docker image to serve some legacy HTML content behind another reverse proxy, and would like to use the `sub_filter` directive to replace text in certain request strings per the [documentation here](https://nginx.org/en/docs/http/ngx_http_sub_module.html).

It appears that the Bitnami Nginx executable is compiled without this module (presumably to minimise the image size). When trying to use this directive, I receive the error `nginx: [emerg] unknown directive "sub_filter" in /opt/bitnami/nginx/conf/server_blocks/site.conf:7`.

I am wondering if this module could be included as part of the Bitnami Nginx Docker image in future updates. I note that the module `ngx_http_sub_module` is included in the official Docker Hub Nginx image.

Related issue: https://github.com/bitnami/bitnami-docker-nginx/issues/112

**Comment by carrodher** [comment]
Hi, thanks for letting us know! I just opened a task to evaluate including this module in the image. We'll update this thread as soon as we have some news.

**Comment by carrodher** [comment]
Hi @ropable, we just released a new NGINX version compiled using `--with-http_sub_module`, you can find it using `latest` or rolling tags like `1.16`. It was released for debian-9 and ol-7.

I will close the issue as solved, please feel free to reopen it if the new version doesn't work as expected.

**Comment by ropable** [comment]
@carrodher Many thanks for the prompt response, and new compiled version of Nginx. Solved my use-case perfectly :)
