### ISSUE TITLE
Gzip types uses deprecated javascript type 

### ISSUE THREAD

**Issue by mmmdreg** [bitnami/bitnami-docker-nginx#125]
In the nginx config, gzip_types includes application/x-javascript and text/javascript, both of which have been deprecated and superseded by application/javascript (which is not included).

This issue is to request addition of application/javascript in addition to the existing types, in order to match the intention of the existing config.

**Comment by andresbono** [comment]
Thanks for noticing, @mmmdreg. We have just opened a PR that fixes it.

Feel free to open a PR or fill an issue if you find another improvements!!
