### ISSUE TITLE
Hardcoded ports

### ISSUE THREAD

**Issue by lzielezinska** [bitnami/bitnami-docker-nginx#127]
Hi,
I am using nginx image and I have two problems to discuss:
The ports in Dockerfile are hardcoded.
`EXPOSE 8080 8443
`
I have set the port to 8000 using env.
`ENV NGINX_HTTP_PORT_NUMBER=8000
`
No matter which ports we used these two are also there:
```
"ExposedPorts": {
                "8000/tcp": {},
                "8080/tcp": {},
                "8443/tcp": {}
            },
```
The second problem occurred when I set CMD. In script entrypoint.sh there is an instruction
```
if [[ "$*" = "/run.sh" ]]; then
    info "** Starting NGINX setup **"
    /setup.sh
    info "** NGINX setup finished! **"
fi
```
It means that when we change CMD from default `CMD [ "/run.sh" ] ` the following scripts won't start, doesn't it? For example in my Dockerfile I wrote:
`CMD ["/bin/sh",  "-c",  "envsubst < /opt/bitnami/nginx/html/assets/settings.template.json > /opt/bitnami/nginx/html/assets/settings.json && exec nginx -g 'daemon off;'"]`
When I check exposed ports, there were only  8080 and 8443 despite I set `ENV NGINX_HTTP_PORT_NUMBER=8000
`
Is it intentional or maybe I understand it in a bad way?

**Comment by juan131** [comment]
Hi @lzielezinska 

What platforms are you using to deploy the NGINX container? 

Despite the ports `8080/8443` are the default ones and they're hardcoded in the Dockerfile, you can access the container through other ports if you use (as you mentioned) the environment variable **NGINX_HTTP_PORT_NUMBER**. 
I guess the JSON file you shared comes from `docker inspect` but please note that even if Docker doesn't recognise you custom port (8000) you should be able to access it.

> Is it intentional or maybe I understand it in a bad way?

I don't fully understand why do you need to overwrite the CMD. I mean, why don't you define your custom environment variables using the `-e` or `--env` flags available in the `docker run` command?  See https://docs.docker.com/v17.12/edge/engine/reference/commandline/run/#set-environment-variables--e-env-env-file

Some basic example:

```console
$ docker run --name nginx --rm -dit -p 8000:8000 -e NGINX_HTTP_PORT_NUMBER=8000 bitnami/nginx
$ docker exec nginx env | grep NGINX_HTTP_PORT_NUMBER
NGINX_HTTP_PORT_NUMBER=8000
$ curl 127.0.0.1:8000
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

**Comment by lzielezinska** [comment]
I wrote Dockerfile for angular app. There is a problem with setting env. I solved this problem with envsubst command which replace address that in have in my code to env API_URL, which I have in my Dockerfile. 

```
ENV API_URL=http://localhost:8080

COPY --from=builder --chown=1001 /app/dist/* /opt/bitnami/nginx/html/

ENV NGINX_HTTP_PORT_NUMBER=8000

CMD ["/bin/sh",  "-c",  "envsubst < /opt/bitnami/nginx/html/assets/settings.template.json > /opt/bitnami/nginx/html/assets/settings.json && exec nginx -g 'daemon off;'"
```
It works well -> the address is correct but now the ports are defaults. I can't use this command in RUN, because it will be impossible to change API_URL with docker run -e.  Not sure if there is an option in docker run that will solve the problem ;(

**Comment by juan131** [comment]
> I can't use this command in RUN, because it will be impossible to change API_URL with docker run -e. Not sure if there is an option in docker run that will solve the problem ;(

So your problem is not defining an environment variable but editing the `/opt/bitnami/nginx/html/assets/settings.json` file instead, is it?

If you check this line (https://github.com/bitnami/bitnami-docker-nginx/blob/master/1.16/debian-9/rootfs/postunpack.sh#L55) you'll se that the directory `/opt/bitnami/nginx/html/` is actually a symbolic link which points to `/app` directory.

You can mount your custom application in the `/app` directory as it's explained in the link below:

https://github.com/bitnami/bitnami-docker-nginx#hosting-a-static-website

This way, you should be able to edit the `settings.json` (or any other file) and then mount it in the image.
