### ISSUE TITLE
Option to disable startup logs

### ISSUE THREAD

**Issue by Kovah** [bitnami/bitnami-docker-nginx#129]
Hi Bitnami team,
currently, the Docker nginx container produces output like this after the start:

```
Welcome to the Bitnami nginx container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-nginx
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-nginx/issues
Send us your feedback at containers@bitnami.com

INFO  ==> ** Starting NGINX setup **
INFO  ==> Validating settings in NGINX_* env vars...
INFO  ==> Initializing NGINX...
INFO  ==> ** NGINX setup finished! **

INFO  ==> ** Starting NGINX **
```

My question is, if there is any way to safely remove or disable those logs? The problem is that I want to access the nginx web logs with a third-party tool, but these startup logs are kinda "polluting" the output, especially if the container is restarted several times.

If there is no way, would you accept a pull request that disables the logs, e.g. by setting a specific environment variable? I thought about something like `DISABLE_STARTUP_LOGS`. If set, the startup script would output nothing and nginx itself is the only application filling the log.

**Comment by rafariossaa** [comment]
Hi @kovah,
  I am creating a internal task to consider your proposal.
  Meanwhile, I think you can use the following workaround.
  - Create a custom nginx.conf and set the access log to a file (eg. /access_log.txt)
  - In the compose mount a file on /access_log.txt
  
  This way you will have a clean access log to pass to any third-party tool.

  Could you give it a try ?

**Comment by Kovah** [comment]
Sure, will try this.

**Comment by Kovah** [comment]
Forgot to reply here. Using external files for nginx seems to be a proper solution. But maybe the idea could be kept for other images, as there might be other apps which do not have an option to save the logs elsewhere.

**Comment by rafariossaa** [comment]
Hi @Kovah,
  Thanks for the suggestion.
  The internal task I created is for study this use case and extend the solution to all the assets.

**Comment by Kovah** [comment]
Great!
Closing this specific request now.
