### ISSUE TITLE
Configure And Use Logrotate

### ISSUE THREAD

**Issue by DomKrulak** [bitnami/bitnami-docker-nginx#130]
I'm taking an interest in using [logrotate](https://linux.die.net/man/8/logrotate) to log nginx's log files and I'm learning as I go.
According to [this blog post](https://docs.bitnami.com/oci/infrastructure/nginx/administration/configure-use-logrotate/) in Bitnami docs states that: 

> Rrecent versions of Bitnami stacks ship logrotate configuration files for all servers.

> If you are using a virtual machine or cloud image, logrotate is already configured and enabled by default.

All I could find in filesystem is `etc/logrotate.d` directory.
So I've installed `logrotate` on `BITNAMI_IMAGE_VERSION="1.16.1-debian-9-r100"`.
`logrotate -v` returns 
`logrotate 3.11.0 - Copyright (C) 1995-2001 Red Hat, Inc.`

By the way I follow [How to Install Logrotate and Configure Nginx Log Rotation](https://linoxide.com/linux-how-to/install-logrotate-configure-nginx-log-rotation/) blog post.

Now I created `nginx` config file in `etc/logrotate.d` directory.
```
/app/logs/access.log {
    create 0644 1001
    daily
    rotate 2
    mail me@gmail.com
    size 1k
    missingok
    notifempty
    compress
    sharedscripts
    postrotate
        /bin/kill -USR1 `cat /run/nginx.pid 2>/dev/null` 2>/dev/null || true
    endscript
}
```
Questionable is
```
postrotate
    /bin/kill -USR1 `cat /run/nginx.pid 2>/dev/null` 2>/dev/null || true
endscript
```
which I don't understand what is going on in `postrotate endscript`. 
I quiet understand to most of logrotate's directives .

I'm not even sure if logrotate is running.
 I've used this command
`logrotate -f /etc/logrotate.d/nginx`
with respond 
`error: Logrotate UID is not in passwd file.`

It would be helpful If I could follow up  some code of conduct to basic configuration and use.

**Comment by juan131** [comment]
Hi @DomKrulak 

> According to this blog post in Bitnami docs states that:
> Recent versions of Bitnami stacks ship logrotate configuration files for all servers.
> If you are using a virtual machine or cloud image, logrotate is already configured and enabled by default.

Please note that documentation applies to VMs and Cloud images but it's not valid for Bitnami containers.

As you'll find in the link below, Bitnami images send the container logs to the `stdout`. I'm afraid that you won't be able to use logrotate on these containers.

- https://github.com/bitnami/bitnami-docker-nginx#logging

When running containers on production (e.g. on Kubernetes), there are solutions such as ELK to collect logs from every container, so you need the logs to be redirected to stdout so the container engine can access them.

**Comment by DomKrulak** [comment]
@juan131 

I see and understand it more now. I have a lot to learn and figure out!

Thanks £ @juan131
