### ISSUE TITLE
SSL certificate generation through Letsencrypt

### ISSUE THREAD

**Issue by srinivasareddyasha** [bitnami/bitnami-docker-nginx#132]
Hi i created my ssl certificates using letsencrypt for my DNS My problem is to be for every 90days i have to do for renewal i can create renewal using Crontab but my main problem is to be when I generated certificate that time its generated for 0.0.0.0/0 but i dont want to regenerate/ renewal this certificate for 0.0.0.0/0 i want this certificate only for my office people i have to access is there any way to create certificates only for specific range they can access Please provide me the best option to create this ssl certificates. Mainly i want to access my application from specific ip range only not from any where(0.0.0.0/0) for port 80 nginx, Please give me solution

**Comment by andresbono** [comment]
Hi @srinivasareddyasha, certificates are usually bound to domain names no matter the origin of the web requests. You will need to configure your DNS + firewall/routing settings to allow access from a restricted set of IPs. We do not offer support on those specific topics.
