### ISSUE TITLE
Unable to start working website with PHP-FPM

### ISSUE THREAD

**Issue by Paullik74** [bitnami/bitnami-docker-nginx#135]
Hi,
I'm on Windows and I'm trying to start my website, here is my files:
```
# docker-compose.yml
version: "3"

services:
    nginx:
        image: bitnami/nginx:latest
        ports:
            - "80:8080"
        volumes:
            - ./:/app
            - ./site.conf:/opt/bitnami/nginx/server_blocks/site.conf
    php:
        image: bitnami/php-fpm:latest
        volumes:
            - ./:/app

```
```
# index.php
<?php
phpinfo();

```
```
# site.conf
server {
    listen 8080;
    server_name localhost;

    root /app;

    location / {
        try_files $uri $uri/index.php;
    }

    location ~ \.php$ {
        # fastcgi_pass [PHP_FPM_LINK_NAME]:9000;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi.conf;
    }
}

```
`docker ps`:
![image](https://user-images.githubusercontent.com/10046079/80303534-1f298f80-87b1-11ea-80ef-80735a431970.png)

When I'm going to `http://localhost`, I get `403 Forbidden` error:
![image](https://user-images.githubusercontent.com/10046079/80303559-6021a400-87b1-11ea-8e8b-cd128ff3be98.png)

And ERROR in NGINX is (from `docker-compose logs nginx`):
```
nginx_1  | 2020/04/26 09:22:06 [error] 30#0: *1 directory index of "/opt/bitnami/nginx/html/" is forbidden, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", host: "localhost"
```

It's so simple I wanna cry, but it's not working for me. I was trying so many things and I'm still lost.

Could please someone help me with that? Why is this happening? Everything is from tutorials for `bitnami/nginx` and `bitnami/php-fpm`. I really don't understand why it's not working. `index.html` is working fine, PHP is a problem.

**Comment by rafariossaa** [comment]
Hi,
  Sorry for the dealy, could you point me to the tutorial you are following ?

**Comment by rafariossaa** [comment]
Hi @Paullik74 ,
  Could you try this docker-compose.yml:
```
# docker-compose.yml
version: "3"

services:
    nginx:
        image: bitnami/nginx:latest
        ports:
            - "80:8080"
        volumes:
            - ./app:/app
            - ./conf/site.conf:/opt/bitnami/nginx/conf/server_blocks/site.conf
    php:
        image: bitnami/php-fpm:latest
        volumes:
            - ./app:/app
```
  To have it more clean, I created a couple of directories, `app` and `conf` and moved `index.php` to `app` and `site.conf` to `conf`. This is not related with the issue but it helps to have a more clean structure.

**Comment by Paullik74** [comment]
Hi @rafariossaa, thx for reply, I'll try it and let you know.

I prepared my files based on https://github.com/bitnami/bitnami-docker-php-fpm#step-2-create-a-server-block and other documentations like for example here https://github.com/bitnami/bitnami-docker-nginx#step-1-write-your-my_server_blockconf-file-with-the-following-content, sorry I know this aren't tutorials, I expressed myself wrong.

**Comment by Paullik74** [comment]
@rafariossaa Unfortunately no change, still 403.

**Comment by rafariossaa** [comment]
Did you delete, not just stop, the container and volumes with `docker-compose down -v` before trying this ?

**Comment by Paullik74** [comment]
I had everything deleted, clean docker.

**Comment by rafariossaa** [comment]
Hi @Paullik74 ,
  Did you tried with the docker-compose.yml I provided. There is a small change in the mounting path with respect to yours:
```
yours:
   - ./site.conf:/opt/bitnami/nginx/server_blocks/site.conf
```
```
mine:
- ./conf/site.conf:/opt/bitnami/nginx/conf/server_blocks/site.conf
```

As you can see the `site.conf` mounting path in the container had changed, note the **/conf/**

**Comment by Paullik74** [comment]
Yes sure, I moved configs to the directories and changed paths in yml. For you it is working?

**Comment by Paullik74** [comment]
@rafariossaa oh my god I'm blind, you are right I had wrong path here all the time :( shame... thank you very much, im closing
