### ISSUE TITLE
Make file/folders writeable by the runtime user

### ISSUE THREAD

**Issue by yntelectual** [bitnami/bitnami-docker-nginx#137]
**Description**

A common usecase for SPA apps running on Nginx is to be able to load the env vars set for the deployment. This is commonly done by an init shell script that does `envsubst` or something similar, that would replace some static file e.g. under `/html/assets/config.json`. When we run this image on Openshift, the container is run under an arbitrary user(with group root), therefore at runtime, we can not write to any of the files or folders e.g. under the `html` directory. 

**Steps to reproduce the issue:**

1. build a docker image, copying static assets and an init shell script to the base image
2. modify CMD to execute the entry point sh on startup, that would replace the env vars in chosen file -  basicaly the entrypoint.ss is something like this
```
envsubst  /opt/bitnami/nginx/html/assets/env.json
/opt/bitnami/scripts/nginx/entrypoint.sh
exec "$@"
```

**Describe the results you received:**

No files/folders under `/opt/bitnami/nginx/html/` are writable by the runtime user. Therefore I need to change permissions using `RUN chmod...` after I copy the static assets which seems repetitive and prone to errors and security issues.
```
COPY --from=build --chown=101:0 /ng-app/dist /opt/bitnami/nginx/html
USER 0
RUN chmod -R g=u /opt/bitnami/nginx/html/
USER 1001
```

**Question**
What are my options to make this work? Could the permissions in the image be set so that a group could write to html and its subfolders? Thanks

**Comment by juan131** [comment]
Hi @yntelectual 

I don't know if you're using the [Bitnami NGINX helm chart](https://github.com/bitnami/charts/blob/master/bitnami/nginx) but I guess you're mounting your custom site at `/app` in a similar way we do for the chart (see https://github.com/bitnami/charts/blob/master/bitnami/nginx/templates/deployment.yaml#L88).

If you're using a volume to mount your site, you can use a "SecurityContext" to control the filesystem ownership on that volume.

Indeed, if you're using a PVC, Openshift will handle that for you by default. I mean, Openshift will create a Persistent Volume using the same arbitrary UID both for the volume filesystem and running the container. So you can do sth like this:

- Use a PVC to ask Openshift for a volume. Openshift will manage that for you assigning the right ownerhsip.
- Mount the volume both on NGINX container and a "initContainer"
- Use the "initContainer" to download your custom website files and put in the volume.
- Then, once the NGINX container starts, it will have the website files on the right path, and it'll be able to read/write on the volume.
