### ISSUE TITLE
Add `application/javascript` to `gzip_types` in `nginx.conf` of `bitnami/nginx:1.16`?

### ISSUE THREAD

**Issue by chengtie** [bitnami/bitnami-docker-nginx#140]
I deployed a website with docker and `bitnami/nginx` as image: https://www.10studio.tech/demo. After deployment, I realized that files like `analyzejs.js` was not gzipped:

[![enter image description here][1]][1]

Here is `docker-compose.yml`:

    version: "3"
    services:
      docusaurus:
        image: bitnami/nginx:1.16
        restart: always
        volumes:
        - ./build:/app
        - ./certs:/certs:ro
        - ./my_server_block.conf:/opt/bitnami/nginx/conf/server_blocks/my_server_block.conf:ro
        ports:
        - "3001:3001"
        - "3002:3002"

Here is `/opt/bitnami/nginx/conf/nginx.conf`, where gzip seems to be enabled:

    I have no name!@8317023de7ec:/app$ cat /opt/bitnami/nginx/conf/nginx.conf
    # Based on https://www.nginx.com/resources/wiki/start/topics/examples/full/#nginx-conf
    # user              www www;  ## Default: nobody
    
    worker_processes  auto;
    error_log         "/opt/bitnami/nginx/logs/error.log";
    pid               "/opt/bitnami/nginx/tmp/nginx.pid";
    
    events {
        worker_connections  1024;
    }
    
    http {
        include       mime.types;
        default_type  application/octet-stream;
        log_format    main '$remote_addr - $remote_user [$time_local] '
                           '"$request" $status  $body_bytes_sent "$http_referer" '
                           '"$http_user_agent" "$http_x_forwarded_for"';
        access_log    "/opt/bitnami/nginx/logs/access.log";
        add_header    X-Frame-Options SAMEORIGIN;
    
        client_body_temp_path  "/opt/bitnami/nginx/tmp/client_body" 1 2;
        proxy_temp_path        "/opt/bitnami/nginx/tmp/proxy" 1 2;
        fastcgi_temp_path      "/opt/bitnami/nginx/tmp/fastcgi" 1 2;
        scgi_temp_path         "/opt/bitnami/nginx/tmp/scgi" 1 2;
        uwsgi_temp_path        "/opt/bitnami/nginx/tmp/uwsgi" 1 2;
    
        sendfile           on;
        tcp_nopush         on;
        tcp_nodelay        off;
        gzip               on;
        gzip_http_version  1.0;
        gzip_comp_level    2;
        gzip_proxied       any;
        gzip_types         text/plain text/css application/x-javascript text/xml application/xml application/xml+rss text/javascript;
        keepalive_timeout  65;
        ssl_protocols      TLSv1 TLSv1.1 TLSv1.2;
    
        include  "/opt/bitnami/nginx/conf/server_blocks/*.conf";
    
        # HTTP Server
        server {
            # port to listen on. Can also be set to an IP:PORT
            listen  8080;
    
            location /status {
                stub_status on;
                access_log   off;
                allow 127.0.0.1;
                deny all;
            }
        }
    }

I finally understand that it is because `gzip_types` did not include `application/javascript` in `nginx.conf`.

Do you have an image that has already fixed this? What solution do you suggest?

  [1]: https://i.stack.imgur.com/0juQV.png

**Comment by rafariossaa** [comment]
Hi @chengtie , 
  Thanks for reporting this issue. I can see you are using nginx 1.16 that is outdated.
  In our 1.17 and 1.18 images the `gzip_types` configuration line is as you indicated.

  Could you try the newer versions ?

**Comment by derMatze82** [comment]
@rafariossaa "application/javascript" must be added to gzip_types in order to get .js files gzipped. This is not the case in latest 1.18.

**Comment by rafariossaa** [comment]
Hi,
   You you update to the latest release ? We have changed the nginx.conf fix this issue.

**Comment by rafariossaa** [comment]
I am closing this issue.
