### ISSUE TITLE
Provide ngx_stream_core_module compiled by default

### ISSUE THREAD

**Issue by bnmrmed** [bitnami/bitnami-docker-nginx#141]
**Description**

HI. I would like to use the nginx stream module to reverse proxy TCP traffic. I have seen [here](https://community.bitnami.com/t/how-to-enable-nginx-stream-module/60245) that the --with-stream option is not used when running the configure command for the bitnami nginx. But considering that the issue goes back to 2016 I was wondering if there has been any changes since then.
Although the standard docker hub nginx image comes built with this option and some others, I would prefer to use bitnami's nginx image if possible.

I get the error unknown directive "stream" when adding a stream block in the nginx.conf.

FTR, I'm using nginx as a side-car container in a k8s pod to proxy TCP traffic to my application or to some other server depending on the port number.

Also I'm curious why the choice of not including such a handy configuration in the image.

Thanks in advance.

**Comment by javsalgar** [comment]
Hi,

Thank you very much for using Bitnami. We tend to be conservatives with the image sizing, that's why we try to add the minimal necessary modules. I will forward this to the engineering team for evaluation. We cannot guarantee an ETA but I will update this ticket as soon as we have more information.

**Comment by javsalgar** [comment]
Hi,

Just a note to le you know that we released a new revision of the container that contains the stream module

```
I have no name!@79ea05e9e5c8:/app$ nginx -V
nginx version: nginx/1.18.0
built by gcc 8.3.0 (Debian 8.3.0-6)
built with OpenSSL 1.1.1d  10 Sep 2019
TLS SNI support enabled
configure arguments: --prefix=/opt/bitnami/nginx --with-http_stub_status_module --with-stream --with-http_gzip_static_module --with-mail --with-http_realip_module --with-http_v2_module --with-http_ssl_module --with-mail_ssl_module --with-http_gunzip_module --with-http_auth_request_module --with-http_sub_module --with-http_geoip_module --add-module=/bitnami/blacksmith-sandox/nginx-module-vts-0.1.18 --add-dynamic-module=/bitnami/blacksmith-sandox/nginx-module-geoip2-3.3.0 --add-module=/bitnami/blacksmith-sandox/nginx-module-substitutions-filter-0.20190806.0 --add-module=/bitnami/blacksmith-sandox/nginx-module-brotli-0.20200423.0
```

Do not hesitate to re-open the ticket if you find any issues

**Comment by bnmrmed** [comment]
Oh! What great news, thank you very much. Will get back to you if I find any issues.
