### ISSUE TITLE
brotli + more_clear_headers

### ISSUE THREAD

**Issue by mnpenner** [bitnami/bitnami-docker-nginx#144]
**Description**

Any chance we can get [brotli](https://github.com/google/ngx_brotli) and [more_clear_headers](https://github.com/openresty/headers-more-nginx-module#more_clear_headers) modules?

**Steps to reproduce the issue:**

1. `ls -alh /opt/bitnami/nginx/modules`
2. Strangely, there's a license at `/opt/bitnami/nginx/licenses/nginx-module-brotli-0.20200423.0.txt` but the `.so` and `load_module` don't seem to exist

**Describe the results you received:**

No brotli :(

**Describe the results you expected:**

Yes brotli :)

**Additional information you deem important (e.g. issue happens only occasionally):**

`more_clear_headers` would be nice too

**Comment by andresbono** [comment]
Hi @mnpenner, thanks for opening this issue. We are going to check it and we will get back to you.

**Comment by andresbono** [comment]
Hi @mnpenner, brotli is statically linked to the nginx binary, for that reason, there is no `.so` files. You can see it is supported if you execute:

```
$ docker run --rm -it --entrypoint nginx bitnami/nginx -V
nginx version: nginx/1.19.0
built by gcc 8.3.0 (Debian 8.3.0-6)
built with OpenSSL 1.1.1d  10 Sep 2019
TLS SNI support enabled
configure arguments: --prefix=/opt/bitnami/nginx --with-http_stub_status_module --with-stream --with-http_gzip_static_module --with-mail --with-http_realip_module --with-http_v2_module --with-http_ssl_module --with-mail_ssl_module --with-http_gunzip_module --with-http_auth_request_module --with-http_sub_module --with-http_geoip_module --add-module=/bitnami/blacksmith-sandox/nginx-module-vts-0.1.18 --add-dynamic-module=/bitnami/blacksmith-sandox/nginx-module-geoip2-3.3.0 --add-module=/bitnami/blacksmith-sandox/nginx-module-substitutions-filter-0.20190806.0 --add-module=/bitnami/blacksmith-sandox/nginx-module-brotli-0.20200423.0
```

`--add-module=/bitnami/blacksmith-sandox/nginx-module-brotli-0.20200423.0`

About including `more_clear_headers`, I have opened an internal task for evaluation and possible implementation. We will keep this issue open until we have more news.

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
