### ISSUE TITLE
image doesn't support including Lua module

### ISSUE THREAD

**Issue by SaravananPerumal23** [bitnami/bitnami-docker-nginx#146]
**Description**

Tried to use 'access_by_lua' directive to handle a POST request and convert to GET method which doesn't work. Unable to get this working even after the module was installed from Dockerfile. Seems to be version conflict between the Module compiled version vs the Nginx version.

**Steps to reproduce the issue:**

1. Dockerfile Content
```Dockerfile
   USER root
   RUN apt-get update -y
   RUN apt-get install -y libnginx-mod-http-ndk=1.10.3 libnginx-mod-http-lua=1.10.3
   USER 1001

   COPY nginx.conf /opt/bitnami/nginx/conf/nginx.conf
   COPY index.html /opt/bitnami/nginx/html/index.html
```
2. Nginx.conf content
```    
    —Specific location section---
     location /welcome {
        if ($request_method = POST ) {
                access_by_lua '
                        ngx.req.read_body()
                        local data = ngx.req.get_body_data()
                        ngx.req.set_uri_args(data)
                ';
            }

            proxy_pass http://localhost;
            proxy_method GET;                    # change method
            #include /etc/nginx/proxy_params.inc; # include some params
        }
```
**Describe the results you received:**

module "/usr/lib/nginx/modules/ndk_http_module.so" version 1014002 instead of 1018000

**Describe the results you expected:**

Should be able to run Docker container with the Nginx

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`: 

```
Docker version 19.03.12, build 48a66213fe
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 59
  Running: 1
  Paused: 0
  Stopped: 58
 Images: 166
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.848GiB
 Name: docker-desktop
 ID: RPED:VQ2X:SJCX:H2DV:ZYM2:WCZ3:L25S:LS4C:QB46:OROJ:2GO2:YF7Y
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 46
  Goroutines: 56
  System Time: 2020-09-10T04:51:43.7241799Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  192.168.99.106:2376
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Docker for MAC

**Comment by carrodher** [comment]
Hi, thanks for creating this issue. I am not sure how can we help you regarding this case. By default, the `bitnami/nginx` image doesn't include lua installed out-of-the-box, if you want to install it you need to do it in your Dockerfile as you're doing, doing that as root is another good point, but I am not sure how we can solve the version issue. Is it not a valid way to be installed with the existing version of NGINX? Please note there is one image for NGINX 1.18 and another one for NGINX 1.19

**Comment by marcosbc** [comment]
Hi @SaravananPerumal23, just a note that we documented how to build and enable custom NGINX modules for the Bitnami NGINX Docker image here: [Adding custom NGINX modules](https://github.com/bitnami/bitnami-docker-nginx#adding-custom-nginx-modules).
