### ISSUE TITLE
possibility to remove the RSA private key from the image

### ISSUE THREAD

**Issue by agarwva2** [bitnami/bitnami-docker-nginx#147]
**Description**

Possibility to remove the RSA private key from the image
**Steps to reproduce the issue:**

1. Image reviewed - bitnami/nginx:1.19.3-debian-10-r27
We observed that the docker image contains RSA Private key at two locations:-
-- /opt/bitnami/nginx/conf/bitnami/certs/server.key
-- /certs/server.key

**Describe the results you received:**

As per our security guidelines docker images should not contain sensitive data such as RSA Private Key

![image](https://user-images.githubusercontent.com/26313523/97237899-66d4b680-17e8-11eb-9f84-ed614f635c2d.png)
![image](https://user-images.githubusercontent.com/26313523/97237911-6c320100-17e8-11eb-9f79-6298d2bb0575.png)

**Comment by miguelaeh** [comment]
Hi @agarwva2 ,
I think that private key does only exists if you mount it as a volume.
Do you know any other better approach to avoid mounting the certificate?

**Comment by agarwva2** [comment]
@miguelaeh - I think the private key is coming from the this image directly, we have not mounted any volume. Is it possible to remove this private key form the base image.

**Comment by miguelaeh** [comment]
Hi @agarwva2 ,
I checked this with the team and we are adding the certificates here to make it easy to configure the image using https for new users for testing purpose.
The certificate is intended to be overwriten by mounting your own certificate. In any case I wlll create an internal task to evaluate if we can generate the certificates on the fly.
Regards.

**Comment by KJLJon** [comment]
I hope no one is actually using these keys and always generating their own (as recommended in the readme).  I honestly think the keys shouldn't even be in the repository to prevent accidental usage.

Anyways, I see this has been on hold for a while now.

@miguelaeh What are your thoughts on removing the keys from this repository, and generating a new key pair inside `run.sh` if one doesn't already exist.

For example, this could be added to `run.sh` before nginx is started:
```bash
if [ ! -f "/opt/bitnami/nginx/conf/bitnami/certs/server.key" ]; then
  openssl req \
    -x509 -nodes -sha512 -days 365 \
    -subj "/CN=localhost" \
    -newkey rsa:2048 \
    -keyout /opt/bitnami/nginx/conf/bitnami/certs/server.key \
    -out /opt/bitnami/nginx/conf/bitnami/certs/server.crt
fi
```

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
