### ISSUE TITLE
Need information about adding module

### ISSUE THREAD

**Issue by serg-bs** [bitnami/bitnami-docker-nginx#150]
**Description**
Default nginx docker image has module ngx_http_perl_module.
Bitnami docker image don't contain this module. 

I could try install module using
https://docs.nginx.com/nginx/admin-guide/dynamic-modules/perl/
https://nginx.org/ru/linux_packages.html
But it look like not convinient way to install module.

I expect some additional extra parameters to turning module. 
May be you have best practice about install module?

**Comment by andresbono** [comment]
Hi @serg-bs, what do you have in mind to ease the installation? Any suggestions are welcome.

I would suggest creating a custom image that extends from `bitnami/nginx`. In the new Dockerfile you can  add the .so library to `/opt/bitnami/nginx/modules` and then modify the main configuration file (`/opt/bitnami/nginx/conf/nginx.conf`) to load the dynamic library.

Does it sound reasonable to you?

**Comment by serg-bs** [comment]
I try 
```
FROM nginx:1.11.3 as base
FROM bitnami/nginx:1.19.4-debian-10-r0

COPY --from=base /usr/lib/nginx/modules/ngx_http_perl_module.so /opt/bitnami/nginx/modules/ngx_http_perl_module.so
USER root
RUN chmod +x /opt/bitnami/nginx/modules/ngx_http_perl_module.so
USER 1001
```
add to nginx.conf
```
load_module modules/ngx_http_perl_module.so;
```
output:
```
2020/12/14 14:51:48 [emerg] 12#0: dlopen() "/opt/bitnami/nginx/modules/ngx_http_perl_module.so" failed (libperl.so.5.20: cannot open shared object file: No such file or directory) in /opt/bitnami/nginx/conf/nginx.conf:7
```
this is not working. See output of 
```
 nginx -V
```
Looks like nginx should be compiled with module.

I found here many similar issue like
https://github.com/bitnami/bitnami-docker-nginx/issues/141
There are problem fixed, but no any commit about. Look like some manual hidden work. 
May be we could ask @javsalgar to write article, how to rebuild bitnami custom nginx image with perl module, or any over, lua for example. I think this functionality should be well documented.

**Comment by marcosbc** [comment]
Hi @serg-bs, we've spent some time investigating how to enable modules for NGINX and realized that our NGINX actually was missing an option for supporting dynamic modules. We just released NGINX `1.19.6-debian-10-r1` and `1.18.0-debian-10-r210` with this supported option.

Now, in order to build a new module, you would have to compile NGINX with that module, then copy the newly generated files onto the Bitnami image.

For example purposes, we're working on documenting how to install new NGINX modules in the container's README, with the `ngx_http_perl_module` case (the module that you want).

Find below a working multi-stage Dockerfile that can be used to build, install and enable NGINX's Perl module (`ngx_http_perl_module`) in the Bitnami image:

```Dockerfile
ARG NGINX_VERSION=1.19.6
ARG BITNAMI_NGINX_REVISION=r1
ARG BITNAMI_NGINX_TAG=${NGINX_VERSION}-debian-10-${BITNAMI_NGINX_REVISION}

FROM bitnami/nginx:${BITNAMI_NGINX_TAG} AS builder
USER root
# Redeclare NGINX_VERSION so it can be used as a parameter inside this build stage
ARG NGINX_VERSION
# Install required packages and build dependencies
RUN install_packages dirmngr gpg gpg-agent curl build-essential libpcre3-dev zlib1g-dev libperl-dev
# Add trusted NGINX PGP key for tarball integrity verification
RUN gpg --keyserver pgp.mit.edu --recv-key 520A9993A1C052F8
# Download NGINX, verify integrity and extract
RUN cd /tmp && \
    curl -O http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz && \
    curl -O http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz.asc && \
    gpg --verify nginx-${NGINX_VERSION}.tar.gz.asc nginx-${NGINX_VERSION}.tar.gz && \
    tar xzf nginx-${NGINX_VERSION}.tar.gz
# Compile NGINX with desired module
RUN cd /tmp/nginx-${NGINX_VERSION} && \
    rm -rf /opt/bitnami/nginx && \
    ./configure --prefix=/opt/bitnami/nginx --with-compat --with-http_perl_module=dynamic && \
    make && \
    make install

FROM bitnami/nginx:${BITNAMI_NGINX_TAG}
USER root
# Install ngx_http_perl_module system package dependencies
RUN install_packages libperl-dev
# Install ngx_http_perl_module files
COPY --from=builder /usr/local/lib/x86_64-linux-gnu/perl /usr/local/lib/x86_64-linux-gnu/perl
COPY --from=builder /opt/bitnami/nginx/modules/ngx_http_perl_module.so /opt/bitnami/nginx/modules/ngx_http_perl_module.so
# Enable module
RUN echo "load_module modules/ngx_http_perl_module.so;" | cat - /opt/bitnami/nginx/conf/nginx.conf > /tmp/nginx.conf && \
    cp /tmp/nginx.conf /opt/bitnami/nginx/conf/nginx.conf
# Set the container to be run as a non-root user by default
USER 1001
```

**Comment by serg-bs** [comment]
Thanks a lot, 
but what about not dymanic modules. For example

**Comment by marcosbc** [comment]
Hi @serg-bs, in that case the previously mentioned approach will not work for you, unfortunately, since you'd need to re-build NGINX on your side.

Could you provide us with the list of modules that you're missing in Bitnami's image that you'd like to see? (apart from ngx_http_perl_module and http_realip_module)

**Comment by marcosbc** [comment]
Hi @serg-bs, by the way, "http_realip_module" is already enabled in the Bitnami NGINX Docker image:

```
$ nginx -V
...
configure arguments: (...) --with-http_realip_module (...)
```

**Comment by serg-bs** [comment]
We use only two modules. 
Thank you for detail explanation!
