### ISSUE TITLE
2020/12/30 11:13:35 [error] 71#71: *3 no resolver defined to resolve xxx.xxx.aliyuncs.com, client: 10.42.5.0, server: nginx.fs.imagedz.com, request: "GET /sit-imagedt-shelf/01/01003fe8a1b79421798b52eb92e4a392.jpg HTTP/1.1", host: "xxx.xxx.xxx.com"

### ISSUE THREAD

**Issue by wyman1217** [bitnami/bitnami-docker-nginx#151]
**Description**
my configure as bellow:
```
       location ~ "/.*imagedt.*/" {
            if ($request_uri ~ "/(.*imagedt.*)/([0-9a-z]{2})/(.*)")
            {
               set $params_1 $1;
               set $params_2 $2;
               set $params_3 $3;
              }
            proxy_pass http://$params_1.xxx.aliyuncs.com/$params_2/$params_3;
       } 
```
I got the error:
```
2020/12/30 11:13:35 [error] 71#71: *3 no resolver defined to resolve xxx.xxx.aliyuncs.com, client: 10.42.5.0, server: nginx.fs.imagedz.com, request: "GET /sit-imagedt-shelf/01/01003fe8a1b79421798b52eb92e4a392.jpg HTTP/1.1", host: "xxx.xxx.xxx.com"
```

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by rafariossaa** [comment]
Hi,
  Can you try to `curl` the `proxy_pass` urls from inside the container?
