### ISSUE TITLE
Using environment variables in configuration

### ISSUE THREAD

**Issue by nijk** [bitnami/bitnami-docker-nginx#154]
I was wondering if there are plans to offer [this environment variable feature](https://github.com/docker-library/docs/tree/master/nginx#using-environment-variables-in-nginx-configuration-new-in-119) at any point in the future?

**Comment by javsalgar** [comment]
Hi,

Thanks for the suggestion. It seems that the link is not working, could you update it? Could you explain your use case?

**Comment by nijk** [comment]
Apologies, the link should be correct now.

I'd like to be able to use environment variables in nginx configuration via templates

**Comment by javsalgar** [comment]
Hi,

Did you try setting these environment variables in the container? If the binary supports it, I don't think the container may need changes.

**Comment by nijk** [comment]
Yes, but it didn't work. From looking through the code of the nginxinc image it looks like they use envsubst on the configs templates as part of their entrypoint scripts. This is a really useful feature that isn't part of the nginx binary from what I can tell.

**Comment by javsalgar** [comment]
Hi,

Ok, now I get it. I will forward this to the engineering team. Right now it is more meant to mount your own site and your own configuration. Which parameters would you like to set using env vars?

**Comment by nijk** [comment]
No problem, I really just raised this issue to find out if it was:

1. Already possible to do this
2. Planned for a release in the near future

If the answer to both of those is no, then I will use the nginxinc container instead.

As far as I'm aware, the envsubst approach means that any use of environment variables in an nginx config template can be replaced so long as those environment variables are available at the time of substitution.

**Comment by javsalgar** [comment]
Hi,

Thanks for the feedback. I will let the engineering team know so we can decide on this feature.

**Comment by ericp-us** [comment]
I second this, as this enables the use of a single code base for multi projects and dev environment quicker to deploy.

**Comment by javsalgar** [comment]
Hi,

I'm afraid it is still in our backlog. As soon as there are updates on this, we will update the ticket.

**Comment by carrodher** [comment]
Thanks for this suggestion. After internal evaluation and due to other priorities, if this feature was not implemented during this time, it is very unlikely we will have the bandwidth to work on it in the mid-term.

Being said that, if you would like to contribute, feel free to create a PR to solve this issue. The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
