### ISSUE TITLE
Server blocks config not working

### ISSUE THREAD

**Issue by MatteoInfi** [bitnami/bitnami-docker-nginx#157]
**Description**

Trying to use this image, but it is not working. There server block config gets ignored

**Steps to reproduce the issue:**

1. Create a custom image and COPY the artifact inside: in the `/build` folder there are react build files

```
FROM bitnami/nginx:1.14.2

COPY --from=stage-02 /app/build /www/build
COPY nginx.conf /opt/bitnami/nginx/conf/server_blocks/nginx.conf

USER 1001

EXPOSE 8080
```

2. My config

```
server {
        listen 8080;
        listen [::]:8080;

        root /www/build;
        index index.html index.htm;

        server_name localhost;

        location / {
                try_files $uri /index.html;
        }
}

```
I have inspected the container and the files are copied in the right folders

**Similar setup is working on the official nginx image**, so the current workaround is to not use this image.

**Describe the results you received:**

Keep seeing the Nginx default screen

**Describe the results you expected:**

To see my app home page

**Version**
- Image version: `1.14.2`

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:40 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:48 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by javsalgar** [comment]
Hi,

I think it has to do with the server name being localhost, which may be colliding with another server directive in the configuration. Just to confirm, could you try using another server name, such as example.com, just to confirm if that's the issue?
