### ISSUE TITLE
User 1001 does not exists in buster distro

### ISSUE THREAD

**Issue by satr** [bitnami/bitnami-docker-nginx#158]
**Description**

Dockerfile command `USER 1001` attempts to set this user as current for the container. 
Dictro `docker.io/bitnami/minideb:buster` (and `debian`) do not have such user:
```
cat /etc/passwd
```
This user need to be created in the Dockerfile. E.g.:
```
RUN groupadd --gid 1001 non-root-group && \
        useradd --gid 1001 --uid 1001 non-root-user 
```

**Steps to reproduce the issue:**

1. run commands: 
```
docker run -it bitnami/nginx cat /etc/passwd
docker run -it bitnami/nginx id
```

**Describe the results you received:**
Command `cat /etc/passwd` does not show user 1001
Command `id` outputs `uid=1001 gid=0(root) groups=0(root)`

**Describe the results you expected:**
Command `cat /etc/passwd` shows user 1001
Command `id` outputs `uid=1001 gid=1001`

**Additional information you deem important (e.g. issue happens only occasionally):**

Example of such fix in [nginx unprivileged](https://github.com/nginxinc/docker-nginx-unprivileged/blob/3b24f45715ae96626d103b389f634678eef08cf7/Dockerfile-debian.template#L16)

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:38 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
...
```

- Output of `docker info`:

```
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 8
  Running: 0
  Paused: 0
  Stopped: 8
 Images: 123
 Server Version: 20.10.7
 Storage Driver: overlay2
...
```

**Comment by carrodher** [comment]
Hi, are you facing any specific issue and because of that, you need to set the user in that way? What is your use case?

In the following links you can find more information about non-root containers and how they work, just in case you find this information useful:
- https://docs.bitnami.com/tutorials/bitnami-best-practices-hardening-containers#root-and-non-root-containers
- https://engineering.bitnami.com/articles/why-non-root-containers-are-important-for-security.html

There are some pros and cons, but in general, it is not needed to do this workaround nor the user should be present in the base image.

**Comment by satr** [comment]
Hi. 
Thank you for shared links, very good articles.
The only concern is uncertainty - which permits user can have. Seems it works fine as non-root, but it look belonging to the `root` group, which is owner of most of folders in the distro. According the [docker doc](https://docs.docker.com/engine/reference/builder/#user)
> When the user doesn’t have a primary group then the image (or the next instructions) will be run with the root group

There are couple reported bugs in past related to users, not existing in `/etc/passwd` (like [this old one](https://bugs.python.org/issue10496)), but seems it is not applicable now. Some drawbacks mentioned in [this article](https://medium.com/redbubble/running-a-docker-container-as-a-non-root-user-7d2e00f8ee15#e295)
If you see mentioned above should not be a problem, please close this issue.

**Comment by carrodher** [comment]
Yep, there are known cons about this approach, but AFAIK it's the standard method followed by the industry at this moment, we can maintain this issue opened just in case there are more users with other cons/issues about this topic; but for my experience, we are using this approach during several years and there were no big issues
