### ISSUE TITLE
This image does not provide by default  ngx_http_dav_module 

### ISSUE THREAD

**Issue by sulabh88** [bitnami/bitnami-docker-nginx#161]
**Description**
nginx image does not contain ngx_http_dav_module 

**Steps to reproduce the issue:**
docker run -it --rm bitnami/nginx nginx -V

does not support ngx_http_dav_module which is there in nginx default image .

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**
--with ngx_http_dav_module

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**
latest 
- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by Mauraza** [comment]
Hi @sulabh88,

The module ngx_http_dav_module is not built by default,  for build with a module you can follow [Adding custom NGINX modules of the README.md ](https://github.com/bitnami/bitnami-docker-nginx/#adding-custom-nginx-modules)
