### ISSUE TITLE
Add module that is not distributed with the NGINX source

### ISSUE THREAD

**Issue by dominikkrulak** [bitnami/bitnami-docker-nginx#168]
I'd like to install the [set misc NGINX module](https://github.com/openresty/set-misc-nginx-module) that is not distributed with NGINX source (there are actually 2 modules I want to install).

I have followed the instruction [adding custom NGINX modules](https://github.com/bitnami/bitnami-docker-nginx#adding-custom-nginx-modules) to Bitnami docker NGINX image and [the module installation](https://github.com/openresty/set-misc-nginx-module#installation) and I'm not sure.
I'm not sure (now I know) whether I defined the correct paths to the modules. I think that I just need to copy modules over to `/opt/bitnami/nginx/modules/` in the base image and `load_module` in `nginx.conf` file.

**Dockerfile**
```Dockerfile
ARG NGINX_VERSION=1.21.4
ARG BITNAMI_NGINX_REVISION=r25
ARG BITNAMI_NGINX_TAG=${NGINX_VERSION}-debian-10-${BITNAMI_NGINX_REVISION}

FROM bitnami/nginx:${BITNAMI_NGINX_TAG} AS builder
USER root
## Redeclare NGINX_VERSION so it can be used as a parameter inside this build stage
ARG NGINX_VERSION
## Install required packages and build dependencies
RUN install_packages dirmngr gpg gpg-agent curl build-essential libpcre3-dev zlib1g-dev libperl-dev wget
## Add trusted NGINX PGP key for tarball integrity verification
RUN gpg --keyserver pgp.mit.edu --recv-key 520A9993A1C052F8
## Download NGINX, verify integrity and extract
RUN cd /tmp && \
    curl -O http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz && \
    curl -O http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz.asc && \
    gpg --verify nginx-${NGINX_VERSION}.tar.gz.asc nginx-${NGINX_VERSION}.tar.gz && \
    tar xzf nginx-${NGINX_VERSION}.tar.gz && \
    wget https://github.com/vision5/ngx_devel_kit/archive/refs/tags/v0.3.1.tar.gz && \
    tar xzf v0.3.1.tar.gz && \
    wget https://github.com/openresty/set-misc-nginx-module/archive/refs/tags/v0.33.tar.gz && \
    tar xzf v0.33.tar.gz
## Compile NGINX with desired module
RUN cd /tmp/nginx-${NGINX_VERSION} && \
    rm -rf /opt/bitnami/nginx && \
    ./configure --prefix=/opt/bitnami/nginx --add-module=/tmp/ngx_devel_kit-0.3.1 --add-module=/tmp/set-misc-nginx-module-0.33 && \
    make && \
    make install

FROM bitnami/nginx:${BITNAMI_NGINX_TAG}
USER root
## Install
COPY --from=builder /opt/bitnami/nginx/modules/set-misc-nginx-module.so /opt/bitnami/nginx/modules/set-misc-nginx-module.so
USER 1001
```
**I'm facing this error**
```
ERROR [stage-1 2/4] COPY --from=builder /opt/bitnami/nginx/modules/set-misc-nginx-module.so /opt/bitnami/nginx/modules/set-misc-nginx-module.so
.
. 
.
failed to compute cache key: failed to walk /var/lib/docker/tmp/buildkit-mount199415285/opt/bitnami/nginx/modules: lstat /var/lib/docker/tmp/buildkit-mount199415285/opt/bitnami/nginx/modules: no such file or directory
```
Also I'd like to add that during first stage build `FROM bitnami/nginx:${BITNAMI_NGINX_TAG} AS builder` I got this error from build state `RUN gpg --keyserver pgp.mit.edu --recv-key 520A9993A1C052F8`.
```
 => ERROR [builder 3/5] RUN gpg --keyserver pgp.mit.edu --recv-key 520A9993A1C052F8                               61.9s
------                                                                                                                  
 > [builder 3/5] RUN gpg --keyserver pgp.mit.edu --recv-key 520A9993A1C052F8:                                           
#6 0.333 gpg: directory '//.gnupg' created                                                                              
#6 0.335 gpg: keybox '//.gnupg/pubring.kbx' created
#6 61.85 gpg: keyserver receive failed: No data
------
executor failed running [/bin/sh -c gpg --keyserver pgp.mit.edu --recv-key 520A9993A1C052F8]: exit code: 2
```
I don't know how but it got fixed when `$ docker pull bitnami/nginx:${BITNAMI_NGINX_TAG}` and than run the above `Dockerfile` again.

**Comment by carrodher** [comment]
What is the exact error you are facing? Are you able to deploy the container and the modules are not installed or are installed but they are not working as expected?

**Comment by dominikkrulak** [comment]
@carrodher container isn't build and I'm not sure if modules are installed. See updated question.

**Comment by miguelaeh** [comment]
Hi @dominikkrulak ,
As you commented, the module is not in our Nginx image. I guess to add that module we would need to enable some flags in the configure script at build time.

**Comment by dominikkrulak** [comment]
Hi @miguelaeh,
No, it's not. [The developer](https://github.com/openresty/set-misc-nginx-module) of the module states that it's not distributed with the NGINX source.

Yes, enabling some flags makes sense. That would intervene to other aspects of image that probably you don't want.
If so I already found another way around but it wouldn't be bad to see how it'd go.

**Comment by javsalgar** [comment]
What was the workaround you found?

**Comment by marcosbc** [comment]
@dominikkrulak Have you tried manually creating that directory in the step before? Note that we compile NGINX so that dynamic modules are  built as well (geoip), so that could be the reason why the folder is not created in the first place.

```
$ nginx -V
nginx version: nginx/1.21.2
built by gcc 8.3.0 (Debian 8.3.0-6)
built with OpenSSL 1.1.1d  10 Sep 2019
TLS SNI support enabled
configure arguments: --prefix=/opt/bitnami/nginx --with-http_stub_status_module --with-stream --with-http_gzip_static_module --with-mail --with-http_realip_module --with-http_v2_module --with-http_ssl_module --with-mail_ssl_module --with-http_gunzip_module --with-threads --with-http_auth_request_module --with-http_sub_module --with-http_geoip_module --with-compat --add-module=/bitnami/blacksmith-sandox/nginx-module-vts-0.1.18 --add-dynamic-module=/bitnami/blacksmith-sandox/nginx-module-geoip2-3.3.0 --add-module=/bitnami/blacksmith-sandox/nginx-module-substitutions-filter-0.20190806.0 --add-module=/bitnami/blacksmith-sandox/nginx-module-brotli-0.20201006.0
```

**Comment by dominikkrulak** [comment]
@marcosbc I can try it and you may be right though. Once I do I'll post update.
