### ISSUE TITLE
How to use plaintext logs?

### ISSUE THREAD

**Issue by sandangel** [bitnami/bitnami-docker-nginx#171]
**Description**

Logs has weird text

**Steps to reproduce the issue:**

1. Deploy docker image on ECS
2. Check Cloudwatch logs

**Describe the results you received:**
<img width="788" alt="image" src="https://user-images.githubusercontent.com/22189661/152076692-54aa42bf-3db5-407f-80f2-7bfea41979df.png">

THe logs looks weird.

**Describe the results you expected:**

The logs should look normal 

**Additional information you deem important (e.g. issue happens only occasionally, environment details, etc.):**

**Comment by juan131** [comment]
Hi @sandangel 

Sorry but I don't fully understand your issue with the logs.

- Are you complaining about how Cloudwatch display the logs?
- Are you complaining about the timestamp?
- Are you complaining about the format used by Bitnami to show logs during the NGINX initialization process?

**Comment by sandangel** [comment]
hi @juan131 , sorry I was not clear. I mean the weird repeating sequence in the log: `[38;5;6m`... I guess that is the escape code for color in the logs. I would like to know how to disable it since I can not find the option in the documentation.

**Comment by sandangel** [comment]
hi @juan131 , could you help me check again this issue?

**Comment by juan131** [comment]
Hi @sandangel 

All these colors modifiers come from the library below which defines the functions we use to generate info/warn/error messages in the containers:

- https://github.com/bitnami/bitnami-docker-nginx/blob/master/1.21/debian-10/prebuildfs/opt/bitnami/scripts/liblog.sh#L5

I guess that Cloudwatch isn't compatible with shell scripting colors, but I'm afraid I'm not familiar with that tool so I can't help you to workaround this issue. I recommend you to contact Cloudwatch support for more info about how to solve this.

**Comment by sandangel** [comment]
@juan131 yeah, I also suspect that's the color code. So I'm asking if there is a way to disable the color, just use plain text. I think it should be supported in the library. For example if there is a variable called `DISABLE_COLOR=1` then we should not print color together with the logs.

**Comment by juan131** [comment]
Hi @sandangel 

I'm afraid they can't be disabled at this moment. Please feel free to contribute with a PR if you consider we should support a way to disable them.
