### ISSUE TITLE
Where is the default server defined and how can I modify/override it?

### ISSUE THREAD

**Issue by pcanning** [bitnami/bitnami-docker-nginx#173]
### Name and Version

bitnami/nginx:1.21.6

### What is the problem this feature will solve?

I tried to ask a question at https://community.bitnami.com/, but when I selected "Containers" at the platform is said to create an issue in GitHub.  If this isn't the appropriate place, please tell me where I can ask this question.

What nginx config file defines the default server for ports 8080 and 8443?  I see a server section for port 8080 in `/opt/bitnami/nginx/conf/nginx.conf`, but doesn't have a `location /` directive, only a `location /status`.  I do see a `location /` directive in `/opt/bitnami/nginx/conf/nginx.conf.default` but its for port 80, and as far as I can tell, `nginx.conf.default` isn't actually used.  I can't find a server section for port 8080 with a `location /` directive or a server section for port 8443 anywhere in the container.  I would like to see the configuration of these defaults servers before I try to change/override them.

Can someone tell me where, in the container, to find the configuration of the default servers for ports 8080 and 8443 with their `location /` directives, and how to override that configuration for both ports?

### What is the feature you are proposing to solve the problem?

Add documentation describing where the configuration of the default servers for ports 8080 and 8443 with their `location /` directives is located in the container, and how to override that configuration.

### What alternatives have you considered?

I tried adding a custom server block with the following content:

```
server {
  listen       80 default_server;
  listen       8443 default_server ssl;

  ssl_certificate      bitnami/certs/server.crt;
  ssl_certificate_key  bitnami/certs/server.key;

  #ssl_session_cache    shared:SSL:1m;
  #ssl_session_timeout  5m;

  #ssl_ciphers  HIGH:!aNULL:!MD5;
  #ssl_prefer_server_ciphers  on;

  location / {
    root   html;
    #index  index.html;
    index  test_index.html;
  }
}
```

changing the index to `test_index.html` which has different content than default `index.html` to verify that this block was taking effect, and it works fine for `https://localhost:8443/`, returning the content of `test_index.html`, but I get `403 Forbidden` for `http://localhost:8080/` and the access log says:
`2022/02/20 06:22:27 [error] 36#36: *4 directory index of "/opt/bitnami/nginx/html/" is forbidden, client: 172.17.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:8080"
172.17.0.1 - - [20/Feb/2022:06:22:27 +0000] "GET / HTTP/1.1" 403  117 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0" "-"`
Any idea why it works for `https://localhost:8443/` but not for `http://localhost:8080/`?

**Comment by alemorcuq** [comment]
The default config file is the one you mentioned: `/opt/bitnami/nginx/conf/nginx.conf`

You can overwrite that configuration by mounting a file yourself, as explained [here](https://github.com/bitnami/bitnami-docker-nginx#full-configuration)

**Comment by pcanning** [comment]
Thanks for your help @alemorcuq. I understand that `/opt/bitnami/nginx/conf/nginx.conf` is the default config file.  That is not my question.

The nginx documentation (https://nginx.org/en/docs/http/request_processing.html) says
`In this configuration nginx tests only the request’s header field “Host” to determine which server the request should be routed to. If its value does not match any server name, or the request does not contain this header field at all, then nginx will route the request to the default server for this port. In the configuration above, the default server is the first one — which is nginx’s standard default behaviour. It can also be set explicitly which server should be default, with the default_server parameter in the [listen](https://nginx.org/en/docs/http/ngx_http_core_module.html#listen) directive`

I see that `/opt/bitnami/nginx/conf/nginx.conf` contains a server block containing a `listen  8080` directive, but it doesn't contain a `location /` directive, and none of the included `/opt/bitnami/nginx/conf/bitnami/*.conf` files do either, so I don't understand how that server block can be used to respond to `http://localhost:8080/`, and I also can't find any server block with a `listen 8443` directive, so i don't know how I'm getting a response for `https://localhost:8443/`

I'm asking where (in what configuration file) are the default servers for ports 8080 and 8443 and `location /` defined?

**Comment by alemorcuq** [comment]
There's no `location /` nor port `8443` defined anywhere. By default, the container doesn't listen on port 8443, so you shouldn't be getting a response for that. How are you deploying the server?

**Comment by pcanning** [comment]
I got confused because the container exposes port 8443, but you're right that the default ngnix configuration in the bitnami/nginx image doesn't seem listen to 8443.

If I deploy the container using `docker run -p 8080:8080 bitnami/nginx:latest` I can access `http://localhost:8080/` and I get back the default "Welcome to nginx! ... Further configuration is required." page.  Similarly if I deploy the container using `docker run -v $(pwd):/app:ro -p 8080:8080 bitnami/nginx:latest` and the current working directory contains a custom `index.html` I can access `http://localhost:8080/` and I get back the custom `index.html`.  If there is no `location /`, how does `http://localhost:8080/` work?

**Comment by alemorcuq** [comment]
For specific questions on how Nginx manages requests I suggest you to post your doubts on the Nginx community. My understanding is that the default values for `root` and `index` are used, but you should be able to find a more complete answer on the official community.
