### ISSUE TITLE
Issue with permission on logs and config file?

### ISSUE THREAD

**Issue by ddevalcourt** [bitnami/bitnami-docker-nginx#174]
### Name and Version

bitnami/nginx:1.21

### What steps will reproduce the bug?

New to docker and nginx, trying to setup the Docker-compose file with the following:

    volumes:
      - /opt/jenkins/nginx/logs:/opt/bitnami/nginx/logs
      - /opt/jenkins/nginx/config/jenkins-nginx-dev.conf:/opt/bitnami/nginx/conf/nginx.conf

I believe these are needed based on errors I was getting.  However now I get permission errors:

[jenkins]$ docker logs -f nginx
nginx 00:17:00.69
nginx 00:17:00.69 Welcome to the Bitnami nginx container
nginx 00:17:00.69 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-nginx
nginx 00:17:00.70 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-nginx/issues
nginx 00:17:00.70
nginx 00:17:00.70 INFO  ==> ** Starting NGINX setup **
nginx 00:17:00.72 INFO  ==> Validating settings in NGINX_* env vars
nginx 00:17:00.72 WARN  ==> **The NGINX configuration file '/opt/bitnami/nginx/conf/nginx.conf' is not writable by current user. Configurations based on environment variables will not be applied.**
nginx 00:17:00.73 INFO  ==> No custom scripts in /docker-entrypoint-initdb.d
nginx 00:17:00.73 INFO  ==> Initializing NGINX
realpath: /bitnami/nginx/conf/vhosts: No such file or directory
nginx 00:17:00.75 INFO  ==> ** NGINX setup finished! **
nginx 00:17:00.76 INFO  ==> ** Starting NGINX **
**nginx: [alert] could not open error log file: open() "/opt/bitnami/nginx/logs/error.log" failed (13: Permission denied)
2022/02/24 00:17:00 [emerg] 1#1: open() "/opt/bitnami/nginx/logs/error.log" failed (13: Permission denied)**

### What do you see instead?

This is preventing the nginx pod from coming up.

Not sure how to correct this and any help or guidance would be appreciated.

**Comment by javsalgar** [comment]
Hi!

Bind-mounting volumes is problematic in non-root containers. Could you ensure that the permissions in the mounted folder are so open that a non-root container can write in it?
