### ISSUE TITLE
Bitnami logs errors on clean start

### ISSUE THREAD

**Issue by llech** [bitnami/bitnami-docker-nginx#175]
### Name and Version

bitnami/nginx:latest

### What steps will reproduce the bug?

1. Derive Docker Image from bitnami/nginx:latest
2. Start docker images (locally or in kubernetes with log aggregator)
3. Messages intended to be info appear as errors in log

### What is the expected behavior?

Container should't log information text as errors.

### What do you see instead?

Following text block is logged as error (to stderr, instead of stdout, copied from Portainer console):
```
[38;5;6mnginx [38;5;5m14:37:37.91 [0m
[38;5;6mnginx [38;5;5m14:37:37.93 [0m[1mWelcome to the Bitnami nginx container[0m
[38;5;6mnginx [38;5;5m14:37:37.94 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-nginx[0m
[38;5;6mnginx [38;5;5m14:37:37.94 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-nginx/issues[0m
[38;5;6mnginx [38;5;5m14:37:37.94 [0m
[38;5;6mnginx [38;5;5m14:37:37.94 [0m[38;5;2mINFO [0m ==> ** Starting NGINX setup **
[38;5;6mnginx [38;5;5m14:37:37.97 [0m[38;5;2mINFO [0m ==> Validating settings in NGINX_* env vars
[38;5;6mnginx [38;5;5m14:37:38.04 [0m[38;5;2mINFO [0m ==> Initializing NGINX
[38;5;6mnginx [38;5;5m14:37:38.09 [0m[38;5;2mINFO [0m ==> ** NGINX setup finished! **
[38;5;6mnginx [38;5;5m14:37:38.11 [0m[38;5;2mINFO [0m ==> ** Starting NGINX **
```
If you have alerting integrated with logging aggregator (eg. in Google Cloud), you get false positives.

**Comment by juan131** [comment]
Hi @llech 

All these logs are printed used the functions available in the library below:

- https://github.com/bitnami/bitnami-docker-nginx/blob/master/1.21/debian-10/prebuildfs/opt/bitnami/scripts/liblog.sh

And, as you mentioned, all the logs are redirected to stderr.

**Comment by llech** [comment]
So the solution would be to define function stdout_print, without `>&2`, and only `error()` (and `warn()` ?) should use sterr_print?

**Comment by juan131** [comment]
@llech we throw logs to stderr for a reason. Let's see that with an example:

- You want to implement a function in bash that returns certain value.
- You want to include in that function the possibility to include "log messages".

Using logs to stderr:

```bash
something() {
  info "something"
  echo yes
}
var="$(something)" # var="yes"
```

Using logs to stdout:

```bash
something() {
  info "something"
  echo yes
}
var="$(something)" # var="something yes"
```
