### ISSUE TITLE
Enable stream_ssl_module

### ISSUE THREAD

**Issue by FineWolf** [bitnami/bitnami-docker-nginx#179]
### Name and Version

bitnami/nginx:1.22.0-debian-11-r3

### What is the problem this feature will solve?

This feature will allow to do SSL/TLS termination for backend services that do not support it.

### What is the feature you are proposing to solve the problem?

Add the `--with-stream_ssl_module` flag to the configure arguments when building Nginx. No additional build dependencies are required (since they are already covered by `--with-stream` and `--with_http_ssl_module`).

### What alternatives have you considered?

We did build our own docker images right now based on the documentation, however since `stream_ssl_module` cannot be dynamically linked, we are losing other modules that are not part of the base nginx install that Bitnami includes.

Since Bitnami's build scripts are not public, we cannot replicate the initial build.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. I will forward it to the engineering team. As soon as we have more news, we will update the ticket.
