### ISSUE TITLE
Reverse proxy tries to load files locally

### ISSUE THREAD

**Issue by Mirabis** [bitnami/bitnami-docker-nginx#22]
```
2016/01/10 00:51:31 [error] 178#0: *5 open() "/opt/bitnami/nginx/html/wp-content/uploads/2013/04/Mirabis_Logo_Simple_256.png" failed (2: No such file or directory), client: 173.245.53.144, server: sinthill.nl, request: "GET /wp-content/uploads/2013/04/Mirabis_Logo_Simple_256.png HTTP/1.1", host: "sinthill.nl", referrer: "https://sinthill.nl/"
2016/01/10 00:51:31 [error] 178#0: *6 open() "/opt/bitnami/nginx/html/wp-content/plugins/essential-grid/public/assets/images/300x200transparent.png" failed (2: No such file or directory), client: 141.101.104.20, server: sinthill.nl, request: "GET /wp-content/plugins/essential-grid/public/assets/images/300x200transparent.png HTTP/1.1", host: "sinthill.nl", referrer: "https://sinthill.nl/"
2016/01/10 00:51:31 [error] 179#0: *8 open() "/opt/bitnami/nginx/html/wp-content/uploads/2015/01/Sinthill_banner.jpg" failed (2: No such file or directory), client: 141.101.104.155, server: sinthill.nl, request: "GET /wp-content/uploads/2015/01/Sinthill_banner.jpg HTTP/1.1", host: "sinthill.nl", referrer: "https://sinthill.nl/"
2016/01/10 00:51:31 [error] 178#0: *7 open() "/opt/bitnami/nginx/html/wp-content/uploads/2015/04/rsz_01.jpg" failed (2: No such file or directory), client: 173.245.53.129, server: sinthill.nl, request: "GET /wp-content/uploads/2015/04/rsz_01.jpg HTTP/1.1", host: "sinthill.nl", referrer: "https://sinthill.nl/"
```
Recently, my sites stopped working out of the blue - around the same time the bump from 1.9.7 to 1.9.9 happened.

Requests go to [ Nginx Proxy ] -> [Wordpress Docker Image]  -> So nginx just serves as a proxy passing the right domain to the right docker image. The docker images already have apache *  - so it just has to redirect.

Not sure which files are needed for debug, but I checked nginx.conf , vhost files, logs etc

**Comment by Mirabis** [comment]
Host OS and version: Ubuntu 15.10 | Linux 4.2.0-23-generic
Docker version (docker version): 1.9.1, build a34a1d5
Output of docker info:
```
Containers: 1
Images: 46
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 48
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-23-generic
Operating System: Ubuntu 15.10
CPUs: 2
Total Memory: 665.8 MiB
Name: nginxproxy
ID: YRC2:G4YH:YY74:HMKO:YG53:7GTV:3X6Q:NNIK:ZANC:Y2J2:HO5R:A2RB
WARNING: No swap limit support
```
Version of this container (echo $BITNAMI_APP_VERSION inside the container)
The command you used to run the container, and any relevant output you saw (masking any sensitive information):
```
nginx:
  image: bitnami/nginx:latest
  volumes:
    - /opt/conf:/bitnami/nginx/conf
    - /opt/logs:/bitnami/nginx/logs
    - /opt/home:/app
  ports:
    - "80:80"
    - "443:443"
  restart: always
```

**Comment by chipironcin** [comment]
Hi @Mirabis 
I see you closed this issue. Were you able to solve it?
Do not hesitate in opening it again if you are still experiencing this issue. We will try to help you with it.

**Comment by Mirabis** [comment]
The container used an user ''www-data' and wordpress folders were 755, files 644. 

But for a strange reason the apache2 user inside the Wordpress container was different, and it couldn't read from the wp-content/cache/* folders. Changing the access to 775 for the cache folder only allowed it to work again. 

Another point of interest was the wp-rocket plugin tried to bypass wordpress to cache files, which worked internally (in the container) with apache2. But I tried to apply the same tweaks to the remote nginx server , which didn't work.

Not sure which of the above solved it in the end, but it works now.

**Comment by chipironcin** [comment]
I am glad you were able to solve the issue.
As you are working with Wordpress and containers I would suggest to take a look at:
[Deploying Wordpress with Kubernetes, Bitnami containers and GCE](https://github.com/bitnami/bitnami-docker/tree/master/gke/wordpress)

We want to hear your feedback about it.

Feel free to open an issue if you find that something is not working as expected or suggest Pull Requests if you feel confident about your changes to fix or improve this repo.

Regards :)
