### ISSUE TITLE
Optionally add Google pagespeed module in container

### ISSUE THREAD

**Issue by Mirabis** [bitnami/bitnami-docker-nginx#23]
Recently a few containers started coming with google pagespeed nginx module, which I'd like to use - but bitnamis ease of use is keeping me from switching.

Any chance it could be added, perhaps by command or ENV option?

**Comment by chipironcin** [comment]
Hi @Mirabis 
Sorry for the late response.
Our Nginx Container Image does ship PageSpeed module but it is not currently enabled.
We have created a PR to add detailed instructions in README.md to enable Pagespeed.
https://github.com/bitnami/bitnami-docker-nginx/pull/24

Summarizing:
Add the following lines inside the `server` directive in the Bitnami Nginx configuration filed located at `/opt/bitnami/nginx/conf/bitnami/bitnami.conf`:
```
pagespeed on;
    # needs to exist and be writable by nginx
    pagespeed FileCachePath /installdir/nginx/var/ngx_pagespeed_cache;
    location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" { add_header "" ""; }
    location ~ "^/ngx_pagespeed_static/" { }
    location ~ "^/ngx_pagespeed_beacon$" { }
    location /ngx_pagespeed_statistics { allow 127.0.0.1; deny all; }
    location /ngx_pagespeed_message { allow 127.0.0.1; deny all; }
```

Then reload the Nginx configuration executing:
`nginx -s reload`

Finally, you can check Pagespeed module is enabled executing the following command:
`curl -I localhost | grep X-Page-Speed`

Let us know if you find any issue in the process.

Regards,
Jorge

**Comment by Mirabis** [comment]
It seemed to load, but my sites go into 502 when visiting admin pages etc.

Disabled it for now (until I have time to test).

**Comment by prydonius** [comment]
@Mirabis were you able to test this out?

**Comment by chipironcin** [comment]
ping @Mirabis

**Comment by Mirabis** [comment]
Ah sorry notification must have gone unnoticed....

Back then I was able to get it to work yes, but currently using a different nginx container :).

**Comment by chipironcin** [comment]
Hi @Mirabis thanks for coming back :)

We'd like to know which nginx container are you currently using and why do you prefer it over Bitnami nginx so we can further improve it to fit user needs.
It is because the other nginx container comes with Pagespeed enabled by default?

Thanks for your feedback!

**Comment by Mirabis** [comment]
@chipironcin A while ago i went back to the default nginx container to use it with Letsencrypt integration. Unfortunately with that one, there seemed to be an issue with multiple hosts... so ended up ditching nginx all together for HaProxy.

So no, i just didn't feel like fiddling with bitnami/letsencrypt integration as the nginx one was plug-play :)

**Comment by prydonius** [comment]
@Mirabis thanks for the feedback, adding letsencrypt support to this image sounds like a great idea!

**Comment by sameersbn** [comment]
closing the issue report.  Feel free to report any issues and/or provide us your valuable feedback.
