### ISSUE TITLE
Doesn't work for me...

### ISSUE THREAD

**Issue by BobbyOrlando** [bitnami/bitnami-docker-nginx#27]
Tried this all afternoon, couldn't get it to work, could you help out, please?

My images & containers
![1](https://cloud.githubusercontent.com/assets/4332841/12873528/abd28c44-cdbf-11e5-975a-f8d806bb79d2.jpg)

All is contained in /var/www/testje

var/www/testje/vhost.conf

`
server {
    listen 0.0.0.0:80;
    server_name docker.dev;

    access_log /bitnami/nginx/logs/yourapp_access.log;
    error_log /bitnami/nginx/logs/yourapp_error.log;

    root /app;

    location / {
        index index.php;
    }

    location ~ \.php$ {
        # fastcgi_pass [PHP_FPM_LINK_NAME]:9000;
        fastcgi_pass yourapp:9000;
        fastcgi_index index.php;
        include fastcgi.conf;
    }
}`

My docker-compose.yml:

`nginx:
  image: bitnami/nginx
  links:
    - phpfpm
  volumes:
    - /var/www/testje/vhost.conf:/bitnami/nginx/conf/yourapp.conf

phpfpm:
  image: bitnami/php-fpm
  volumes:
    - /var/www/testje/src:/app
`

But it doesn't work when I
`docker-compose up -d`

![2](https://cloud.githubusercontent.com/assets/4332841/12873553/6379595e-cdc0-11e5-92d3-5993e09582af.jpg)

**Comment by prydonius** [comment]
Hey @BobbyOrlando,

Looks like you need to change the following line in your vhost:
`fastcgi_pass yourapp:9000;` to `fastcgi_pass phpfpm:9000;`, or you can change the link in you docker-compose file to `phpfpm:yourapp`.

You can read more about how to set this up here: https://github.com/bitnami/bitnami-docker-php-fpm#step-3-run-the-nginx-image-and-link-it-to-the-php-fpm-server

Does that fix your issue?

**Comment by BobbyOrlando** [comment]
Made it work with this config eventually, thanks for the help, appreciate it

`web:
  image: test/nginx
  ports:
    - "8080:80"
  volumes:
    - /var/www/test/src:/var/www
    - /var/www/test/conf/vhost.conf:/etc/nginx/sites-enabled/vhost.conf
    #- /var/www/test/conf/default:/etc/nginx/sites-available/default
  links:
    - php

php:
  image: nmcteam/php56
  volumes:
    - ./conf/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - /var/www/test/src:/var/www
    #- /var/www/test/conf/php.ini:/etc/php5/fpm/php.ini
  expose:
    - "9000"
  links:
    - db`
