### ISSUE TITLE
Location of access and error logs?

### ISSUE THREAD

**Issue by nomisbeme** [bitnami/bitnami-docker-nginx#5]
The documentation says the following nginx config entries should work:

    access_log /logs/yourapp_access.log;
    error_log /logs/yourapp_error.log;

But they don't. I just commented out these entries but it would be nice to preserve these logs somewhere.

**Comment by prydonius** [comment]
Thanks @nomisbeme, I've updated the vhost in the PHP-FPM example to reflect the correct log location.
