### ISSUE TITLE
`nami` is not in the path in some environments

### ISSUE THREAD

**Issue by chipironcin** [bitnami/bitnami-docker-nginx#58]
While deploying bitnami/bitnami-docker-nginx container in Pivotal CloudFoundry, an error appeared during installation of the Nami Module:

> -bash: nami: command not found

I see Bitnami is adding `nami` to the PATH in the base image, at https://github.com/bitnami/stacksmith-base/blob/master/minideb/jessie/Dockerfile#L36

But it seems Pivotal CloudFoundry makes a few modifications to the environment to make it more secure, so `PATH=/bin:/usr/bin` at runtime.

Bitnami Nginx also modifies the path in the Dockerfile at https://github.com/bitnami/bitnami-docker-nginx/blob/master/Dockerfile#L15

Suggested workarounds:

1. Modify the PATH at runtime in `app-entrypoint.sh` for every bitnami-docker-XXXX and add `/opt/bitnami/nami/bin`
2. (More generic) Modify the PATH at runtime in `entrypoint.sh` for `nami` (in bitnami/stacksmith-base) and in `app-entrypoint.sh` for every bitnami-docker-XXXX

**Comment by sameersbn** [comment]
I don't understand how changing the `PATH` environment would make the container execution more secure :stuck_out_tongue:

**Comment by chipironcin** [comment]
So you cannot execute Nami for example :stuck_out_tongue_closed_eyes:

**Comment by chipironcin** [comment]
I think this issue is still valid cc/ @sameersbn @carrodher

**Comment by juan131** [comment]
Hi @chipironcin 

Bitnami NGINX image does not use Nami anymore. Please note that all the initialisation logic has been moved to Bash scripts. 

You can find the corresponding Bash scripts in the link below:

https://github.com/bitnami/bitnami-docker-nginx/tree/master/1.14/debian-9/rootfs

**Comment by chipironcin** [comment]
Thank you @juan131 ! Didn't realize 😅  Keep up the good work!
