### ISSUE TITLE
lol question: where i put my files?

### ISSUE THREAD

**Issue by EnricoSx** [bitnami/bitnami-docker-nginx#63]
ubuntu server 16.04
i start bitnami/nginx 1.10.3-r0 container with map 
host: /home/enrico/SITI -> container: 	/bitnami/nginx
create try copy my index.html in
/home/enrico/SITI
/home/enrico/SITI/conf
/home/enrico/SITI/conf/vhosts
restart server and container, but not load my index.html

**Comment by prydonius** [comment]
Hi @EnricoSx,

The mount path in the container for serving static files is `/app`. See https://github.com/bitnami/bitnami-docker-nginx#hosting-a-static-website for more information.

**Comment by EnricoSx** [comment]
but i read this

```
Notable Changes

1.10.0-r0

All volumes have been merged at /bitnami/nginx. Now you only need to mount a single volume at /bitnami/nginx for persistence.
```

**Comment by EnricoSx** [comment]
work with /app thanks 👍

**Comment by prydonius** [comment]
@EnricoSx, ah I understand your confusion, that message is misleading. We used to have different mount points for `conf` (nginx configuration, e.g. vhosts) and `logs`, and these have been merged into a single mount point, however `/app` is still used as the working directory for the files. I will update the README to make this more clear.

Thanks for reporting!
