### ISSUE TITLE
Question 2: where is MYsql ect...?

### ISSUE THREAD

**Issue by EnricoSx** [bitnami/bitnami-docker-nginx#65]
in this page
https://bitnami.com/stack/nginx
it's write:
`Bitnami Nginx Stack provides a complete PHP, MySQL and Nginx development environment that can be launched in one click. It also bundles phpMyAdmin, SQLite, ImageMagick, FastCGI, Memcache, GD, CURL, PEAR, PECL and other components`
but "Nginx Docker Container" not contain it, right?

**Comment by sameersbn** [comment]
@EnricoSx 

> but "Nginx Docker Container" not contain it, right?

Yes, that is correct. With docker containers users prefer launching separate container for each type of service. These distinct services can be linked together using docker networking features or using docker links (deprecated).

Please take a look at our [bitnami/php-fpm](https://github.com/bitnami/bitnami-docker-php-fpm) and [bitnami/mariadb](https://github.com/bitnami/bitnami-docker-mariadb) docker images. We also have a [bitnami/mysql](https://github.com/bitnami/bitnami-docker-mysql) if that's your poison of choice :wink:

**Comment by EnricoSx** [comment]
good :D but this page https://bitnami.com/stack/nginx It does not explain well.
grazie

**Comment by sameersbn** [comment]
@EnricoSx Thanks for taking the time to bring the issue to our attention. We really appreciate your inputs  and will be working on fixing the description.

**Comment by sameersbn** [comment]
@EnricoSx I would like to know your thoughts on whether you would prefer Bitnami to provide a Docker image with MySQL, PHP and NGINX bundled in a single image (similar to the VM offering)?.

With Docker our focus has been to use separate containers for each of these services as it's generally what users deploying containers expect. We are very interested in knowing what your thoughts on the subject are.
