### ISSUE TITLE
nginx supplies X-Frame-Options SAMEORIGIN

### ISSUE THREAD

**Issue by interone-ms** [bitnami/bitnami-docker-nginx#75]
**Description**

With persistent config (via mounting the nginx config directory), there is no way to disable X-Frame-Options header. It is added in `/bitnami/nginx/conf/nginx.conf` line 19, which is recreated during the image boot.

**Steps to reproduce the issue:**

1. Create persistent instance, start it once so the conf directory gets created
2. Stop instance, modify nginx.conf (e.g. delete the line), start instance

**Describe the results you received:**

Config directive reappears in file, X-Frame-Options gets sent.

**Describe the results you expected:**

Config directive does not appear any more. X-Frame-Options header does not appear in response any more.

**Version**

- Output of `docker version`:

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64
```

- Output of `docker info`:

```
Containers: 31
 Running: 9
 Paused: 0
 Stopped: 22
Images: 73
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-514.6.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 27.32 GiB
Name: xxxxx
ID: xxxxx
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by dbarranco** [comment]
Hi @interone-ms 

Thank you so much for the effort of sharing with us all the information, we appreciate it so much.

Could you tell us how did you stopped and started the container?

I modified the `nginx.conf` and I stopped the container with `docker-compose down`. Then I started it again with `docker-compose up` and the line was deleted, so the configuration is persisted.

Best regards.

**Comment by msmuenchen** [comment]
Hi,

I'm running the container in a DC/OS environment - I will try to reproduce it in a pure Docker environment though and keep you updated.

Thanks!
