### ISSUE TITLE
Dynamic Nginx Modules

### ISSUE THREAD

**Issue by rolandsaven** [bitnami/bitnami-docker-nginx#82]
I would like to use the image filter module which is a dynamic module since version 1.9.11. I was wondering if there is a quick way to enable it in the config? (like pagespeed) Is it compiled in this docker image at all?

Thanks

**Comment by javsalgar** [comment]
Hi. Thanks for reporting. The image filter module is not included in our container and we do not have short-term plans to include it. As an alternative, you can use blacksmith to build a `nginx` container tailored to your requirements. Here you can find a guide on how to do it: https://github.com/bitnami/blacksmith/blob/master/docs/Blacksmith.md#examples

**Comment by rolandsaven** [comment]
Awesome, thanks for getting back quickly and for the guide. I'll look into it.

I think we can close it then.
