### ISSUE TITLE
Permission error after adding custom configuration

### ISSUE THREAD

**Issue by migmartri** [bitnami/bitnami-docker-nginx#87]
I have a Dockerfile that adds a custom nginx.conf at build time but at runtime I get the error

```
 docker run --name frontend-production frontend-production
...
nami    INFO  Initializing nginx
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/nginx/conf/bitnami'
```

I am assuming that this is related to the fact that the container does not run as root anymore but I can not find information in the readme file about what user/permissions needs to be mapped on those files to work properly. I figured out that the user used to run the container is the user 1001 by doing:

```
I have no name!@0e82e2e31ba4:/opt/bitnami/nginx/html$
sudo users
sudo: unknown uid 1001: who are you? 
```

See below an extract of the dockerfile

```
# Stage 1: Compile frontend application
...
# Stage 2: Wrap static content by using the NGINX image.
FROM bitnami/nginx:1.12.1-r2
COPY --from=builder /app/build /app
COPY deployment/build/frontend/rootfs /
```

**Comment by migmartri** [comment]
This error is reproducible in any linux host using the default user (1000)

```
ocker run -v /tmp/nginx2:/bitnami bitnami/nginx                                            

Welcome to the Bitnami nginx container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-nginx
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-nginx/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing nginx
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/nginx'
```

**Comment by tompizmor** [comment]
Yes, this is happening because we switched to a non-root container. Mounting a single file should work though. Would the following work for you?

```
docker run -v /tmp/nginx2/conf/nginx.conf:/bitnami/nginx/conf/nginx.conf bitnami/nginx
```

I will check alternatives to be able to mount the whole `conf/ `folder instead of a single file.

**Comment by prydonius** [comment]
@migmartri given you're doing this at build time, you can fix the permissions with a `RUN chmod -R g+rwX /bitnami/nginx` (probably need to switch to `USER root` and then back again)

**Comment by tompizmor** [comment]
@adnan he basically did that but found a different issue before https://github.com/bitnami/bitnami-docker-nginx/issues/88
