### ISSUE TITLE
Using sudo during build

### ISSUE THREAD

**Issue by migmartri** [bitnami/bitnami-docker-nginx#88]
In order to workaround the permissions errors explained [here](https://github.com/bitnami/bitnami-docker-nginx/issues/87), I tried to run a sudo statement to change the file owner to match the one in the container but get the following error at build time.

```
Step 8/9 : COPY deployment/build/frontend/rootfs /
 ---> Using cache
 ---> 52526968553b
Step 9/9 : RUN sudo chown 1001:1001 -R /bitnami
 ---> Running in 10abae962ea8
sudo: unknown uid 1001: who are you?
The command '/bin/sh -c sudo chown 1001:1001 -R /bitnami' returned a non-zero code: 1
```

Wrapping the chown between USER ROOT USER 1001 statements makes the trick but it does not seem a proper solution since most people they will not know what user they should to rollback to.

Also, if you forget to rollback to the user 1001, the container postInstallation script fails.

See below an extract of my Dockerfile.

```
# Stage 1: Compile frontend application
FROM bitnami/node:6.11.1-r0 as builder
COPY frontend/ /app
...

# Stage 2: Wrap static content by using the NGINX image.
FROM bitnami/nginx:1.12.1-r2
COPY --from=builder /app/build /app
COPY deployment/build/frontend/rootfs /
RUN sudo chown 1001:1001 -R /bitnami
```

**Comment by prydonius** [comment]
Switching to root and back again is the correct way of doing this. Also, if you intend to the run this container in an environment that assigns a random UID (such as OpenShift), don't treat 1001 as a real user. Instead, simply give the root group rwX permissions (chmod -R g+rwX /bitnami).

What error are you getting if you forget to rollback to 1001?

**Comment by rlee0524** [comment]
@prydonius I've tried several ways to "switch to root" and back.  Can you provide instructions?  `su - root` does not work because it cannot determine user name.

**Comment by prydonius** [comment]
@rlee0524 you won't be able to do it from within the container, it needs to be done when starting the container `docker run --user root bitnami/nginx`, or by creating a Dockerfile that does:

```
FROM bitnami/nginx
USER root
# do something
USER 1001
```
