### ISSUE TITLE
URL root not forwarded to index.php

### ISSUE THREAD

**Issue by derBobby** [bitnami/bitnami-docker-nginx#92]
When I load the root url (https://<url>/) without any php-site given nginx does not forward the request to the php-fpm container. Following the instructions from [here](https://hub.docker.com/r/bitnami/php-fpm/) I expected that this should work.

So it looks like https://<url>/index.php loads the correct site via php-fpm container.
And https://<url>/ loads the default nginx page from the nginx container.

I could fix this for me with this 301 location redirect. But I guess that this should not be necessary and I just got an error somewhere?

```
    server {
      listen 0.0.0.0:8888;
      server_name <url>;
    
      root /app;
    
      location / {
        return 301 http://<url>/index.php;
      }
    
      location ~ \.php$ {
        fastcgi_pass phpfpm:9000;
        fastcgi_index index.php;
        include fastcgi.conf;
      }
    }
```

**Comment by juan131** [comment]
Hello @derBobby 

You're right! Since you're only redirecting the **php** files to the PHP-FPM container which contains the web application, it's necessary to redirect the requests somehow. The **index** directive is not enough. 

You can also use the **try_files** directive (http://nginx.org/en/docs/http/ngx_http_core_module.html#try_files):

```
location / {
    try_files $uri $uri/index.php;
    # return 301 http://$server_name/index.php;
  }
```

**Comment by derBobby** [comment]
Thank you **try_files** also worked for me.

Should this not be default for this container? Or shouldn't there be at least a comment on this? I guess not all visitors of websites are typing inde.php in the address bar. ;)

**Comment by juan131** [comment]
I updated the README.md file internally and once a new version of the PHP-FPM Container is released, it will be updated. Thanks for reporting it.
