### ISSUE TITLE
Pagespeed is broken in bitnami/nginx:lastest

### ISSUE THREAD

**Issue by Darkknight33** [bitnami/bitnami-docker-nginx#93]
**Description**

Pagespeed is broken in bitnami/nginx:lastest

**Steps to reproduce the issue:**

1. deploy bitnami/nginx

docker-compose.yaml
version: '2'

services:
  nginx:
    image: 'bitnami/nginx:latest'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - nginx_site:/app
      - nginx_data://bitnami

2. Edit nginx.conf add in (copied from readme):

  pagespeed on;
  # needs to exist and be writable by nginx
  pagespeed FileCachePath /installdir/nginx/var/ngx_pagespeed_cache;
  location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" { add_header "" ""; }
  location ~ "^/ngx_pagespeed_static/" { }
  location ~ "^/ngx_pagespeed_beacon$" { }
  location /ngx_pagespeed_statistics { allow 127.0.0.1; deny all; }
  location /ngx_pagespeed_message { allow 127.0.0.1; deny all; }

3. Restart Nginx container

**Describe the results you received:**

Pagespeed is not enabled. Logs record:

```
INFO  ==> Starting nginx...
nginx: [emerg] unknown directive "pagespeed" in /opt/bitnami/nginx/conf/nginx.conf:78
2017/12/28 23:53:40 [emerg] 22#0: unknown directive "pagespeed" in /opt/bitnami/nginx/conf/nginx.conf:78
```

**Describe the results you expected:**

Pagespeed to be enabled

**Additional information you deem important (e.g. issue happens only occasionally):**

Deployed via Rancher with custom service. In the nginx.conf exists a slightly different version of the pagespeed conf than the one included in the readme. It also gives the same error in the log. 

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.4
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:24:58 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.4
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:24:58 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

- Output of `docker info`:

```
Containers: 12
 Running: 12
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 17.09.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: v0.13.2 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 4.13.16-coreos-r2
Operating System: Container Linux by CoreOS 1576.4.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.3MiB
Name: **********
ID: DSBL:OABO:6AZQ:RQKL:23CY:2VXY:DJW7:KV23:2GYD:PAFD:CCOS:CCW2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

VPS server from cloud provider

**Comment by chipironcin** [comment]
Hello @Darkknight33 

I am sorry to asses that the documentation on enabling Pagespeed on the Bitnami Nginx container is outdated and refers to an early version of this container which actually had support for Pagespeed.

The current container does not ship Pagespeed.
I have opened an internal task for updating the documentation and find a proper way of adding Pagespeed support to this image.

**Comment by tompizmor** [comment]
Hi @Darkknight33,

I am afraid that due to compatibility issues between Pagespeed and the current Nginx version is not straightforward to add it to the container again. 
We have updated the documentation to avoid future confusions.
