### ISSUE TITLE
directory index of "/opt/bitnami/nginx/html/" is forbidden

### ISSUE THREAD

**Issue by 18601673727** [bitnami/bitnami-docker-nginx#95]
On a ubuntu machine, `sudo docker-compose up` and open url in browser, got 403
```
2018/01/21 02:47:27 [error] 29#0: *1 directory index of "/opt/bitnami/nginx/html/" is forbidden, client: 192.168.2.227, server: , request: "GET / HTTP/1.1", host: "xxx.com"
```
`sudo docker exec -it 7bf /bin/bash`
```
I have no name!@7bfa928a1cc5:/opt/bitnami/nginx$ ls -al
total 29
drwxrwxr-x 1 root root    4096 Jan 21 02:47 .
drwxr-xr-x 1 root root    4096 Oct 17 18:34 ..
lrwxrwxrwx 1 1001 root      19 Jan 21 02:47 conf -> /bitnami/nginx/conf
drwxr-xr-x 2 1001 root    4096 Jan 21 02:47 extra
drwxr-xr-x 1  501 dialout  952 Jan 21 02:12 html
drwxrwxr-x 2 root root    4096 Oct 17 18:34 licenses
drwxrwxr-x 1 root root    4096 Oct 17 18:34 logs
drwxrwxr-x 2 root root    4096 Oct 17 18:34 sbin
drwxr-xr-x 7 1001 root    4096 Jan 21 02:53 tmp
I have no name!@7bfa928a1cc5:/opt/bitnami/nginx$ 
```
Driven crazy, somebody help..

**Comment by juan131** [comment]
What URL did you use on your browser? I could access without any problem to http://127.0.0.1/index.html after running `docker-compose up`.

Please note that I'm accessing to `/opt/bitnami/nginx/html/index.html` by browsing to http://127.0.0.1/index.html

**Comment by pisarenko-bo** [comment]
Hello! I have same error when deploy to kubernetes. It appears when i try to mount persistent volume for my future static site to /app folder. 

`2019/01/27 18:30:04 [error] 31#0: *1 directory index of "/app/" is forbidden, client: 10.1.1.1, server: , request: "GET / HTTP/1.1", host: "10.1.1.26:8080"` 

Pod doesn't start with error:
`Readiness probe failed: HTTP probe failed with statuscode: 403`

Will be grateful for any help.

**Comment by pisarenko-bo** [comment]
Thanks for reply. There is only vhost setting in my value.yaml.  I used this chart, but I modified deployment.yaml and added PVC for disk mount. I found where was my problem. When I mount disk in "/app" folder then all files in this folder erase and the readiness probe fail because index.html not found.

**Comment by juan131** [comment]
> I found where was my problem. When I mount disk in "/app" folder then all files in this folder erase and the readiness probe fail because index.html not found.

Great! I'm glad you were able to find the reason why it's failing.

Please do not hesitate to let us know if you require further assistance.
