### ISSUE TITLE
could not open error log file: open() "/opt/bitnami/nginx/logs/error.log" failed (13: Permission denied)

### ISSUE THREAD

**Issue by xxrt** [bitnami/bitnami-docker-nginx#97]
when I run this image as root user, it reports error, how can I fix it?

[~]$ docker run -P bitnami/nginx:latest                                                                                                                                                                   

Welcome to the Bitnami nginx container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-nginx
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-nginx/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing nginx
nginx   INFO  ==> nginx.conf not found. Applying bitnami configuration...
nami    INFO  nginx successfully initialized
INFO  ==> Starting nginx... 
nginx: [alert] could not open error log file: open() "/opt/bitnami/nginx/logs/error.log" failed (13: Permission denied)
2018/02/26 10:00:06 [emerg] 31#0: open() "/opt/bitnami/nginx/logs/error.log" failed (13: Permission denied)

**Comment by xxrt** [comment]
and I create group docker and then add another user to that group, it is the same result

**Comment by jotamartos** [comment]
Hi @xxrt,

Sorry but we tried to reproduce the issue but we couldn't do it. We started the NGINX docker container  using the non-root and root user in different directories and the container worked fine in all the situations. In order to know more about the issue, could you please share with us the following information? 

- In order to receive debug messages when launching the container, could you please add this option when launching the command?

```
docker run -P -e NAMI_LOG_LEVEL=trace bitnami/nginx:latest
```

- The default one uses a non-root user (1001) to run the server, could you please use this option to run the web server using the root account inside the container?

```
docker run -P -e NAMI_LOG_LEVEL=trace -u root bitnami/nginx:latest
```

- Which Operating System are you using in your local system?
- Which Docker's version are you using?

```
docker version
docker info
```

Thanks,
Jota

**Comment by xxrt** [comment]
Thanks for your reply @jotamartos 

I tried the command "docker run -P -e NAMI_LOG_LEVEL=trace bitnami/nginx:latest" and it output this

[~]$ docker run -P -e NAMI_LOG_LEVEL=trace bitnami/nginx:latest                                                                                                                                           

Welcome to the Bitnami nginx container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-nginx
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-nginx/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing nginx
nginx   TRACE [prepareDataToPersist] Preparing /opt/bitnami/nginx/conf to persist in /bitnami/nginx/conf
nginx   INFO  ==> nginx.conf not found. Applying bitnami configuration...
nami    INFO  nginx successfully initialized
INFO  ==> Starting nginx... 
nginx: [alert] could not open error log file: open() "/opt/bitnami/nginx/logs/error.log" failed (13: Permission denied)
2018/02/28 01:21:21 [emerg] 32#0: open() "/opt/bitnami/nginx/logs/error.log" failed (13: Permission denied)

Where should I get other logs that you want?

And using a root user inside the container with command "docker run -P -e NAMI_LOG_LEVEL=trace -u root bitnami/nginx:latest", it seems that there is no errors like above.

[~]$ docker run -P -e NAMI_LOG_LEVEL=trace -u root bitnami/nginx:latest                                                                                                                                   

Welcome to the Bitnami nginx container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-nginx
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-nginx/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing nginx
nginx   TRACE [prepareDataToPersist] Preparing /opt/bitnami/nginx/conf to persist in /bitnami/nginx/conf
nginx   INFO  ==> nginx.conf not found. Applying bitnami configuration...
nami    INFO  nginx successfully initialized
INFO  ==> Starting nginx... 

And this is my operation system:
CentOS release 6.8 (Final).

This is my Docker info:
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d/1.7.1
OS/Arch (server): linux/amd64

**Comment by jotamartos** [comment]
Hi @xxrt,

Thank you for sharing the output of the commands.

> Where should I get other logs that you want?

I mentioned the "NAMI_LOG_LEVEL" option to receive more information in case something fails before starting NGINX but it seems everything is fine before starting the server.

> [~]$ docker run -P -e NAMI_LOG_LEVEL=trace -u root bitnami/nginx:latest

This command starts NGINX without problems in your machine so you can start using that from now on to start it. As I mentioned before, NGINX will use the root user to run. 

> And this is my operation system:
> CentOS release 6.8 (Final).
> 
> This is my Docker info:
> Client version: 1.7.1
> Client API version: 1.19

We couldn't reproduce your issue using one of the latest Docker's versions. In this case, your Docker's version was released in 2015 and it can be affecting the deployment. Could you try using a newer version?

Thanks,
Jota
