### ISSUE TITLE
Using Lets Encrypt to generate Custom Certificates

### ISSUE THREAD

**Issue by HeadBanging** [bitnami/bitnami-docker-nginx#98]
**Description**

I've tried to follow the instructions in the section 'Using custom SSL certificates' but I can't get Lets Encrypt to work with the container.

There aren't any instructions provided, as far as I can tell, so I've tried to wing it.  Definitive Bitnami instructions would be very helpful.  Note that I am using hosting multiple websites and so I will eventually need to install certificates for multiple domain names.

**Steps to reproduce the issue:**

I've tried various methods, but the one that I thought had most promise was using certbot with the following settings outside docker, the idea being to generate the certificates in order to use them according to the instructions on this site.

```
./certbot-auto certonly --cb-auto-has-root --standalone --cert-name <mywebsite>.com -d www.<mywebsite>.com -d <mywebsite>.com --agree-tos -m support@<mywebsite>.com --rsa-key-size 4096
```

I also tried running it inside the container as follows:

```
docker exec -i -t lempcompose_nginx_1 /certificates/certbot-auto certonly --cb-auto-has-root --standalone --cert-name <mywebsite>.com -d www.<mywebsite>.com -d <mywebsite>.com --agree-tos -m support@<mywebsite>.com --rsa-key-size 4096
```

**Describe the results you received:**

Running outside the container returns:
```
Requesting to rerun ./certbot-auto with root privileges...
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for www.<mywebsite>.com
http-01 challenge for <mywebsite>.com
Cleaning up challenges
Problem binding to port 80: Could not bind to IPv4 or IPv6.
```

Running inside the container returns:
```
Requesting to rerun /certificates/certbot-auto with root privileges...
sudo: unknown uid 1001: who are you?
```

**Describe the results you expected:**

I expected certificates to be generated so that I could use them with my container.

**Version**

- Output of `docker version`:

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Containers: 24
 Running: 3
 Paused: 0
 Stopped: 21
Images: 20
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-116-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 990.8 MiB
Name: Aitherios
ID: TVRZ:OIN2:PHUQ:OZOC:XA7D:CMJM:POLM:YN36:3J6G:TQLN:6R3O:HB3W
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.7.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by juan131** [comment]
Try following this instructions:

* Create a container with Bitnami NGINX (`docker run --name nginx --user root bitnami/nginx:latest`)
* Connect to the container (`docker exec -it nginx bash`)
* Download a Golang Let's Encrypt client:

```
install_packages wget xz-utils
cd /tmp
curl -s https://api.github.com/repos/xenolf/lego/releases/latest | grep browser_download_url | grep linux_amd64 | cut -d '"' -f 4 | wget -i -
tar xf lego_linux_amd64.tar.xz
mv lego_linux_amd64 /usr/local/bin/lego
```

* Generate a certificate:

```
lego --email="EMAIL-ADDRESS" --domains="DOMAIN" --path="/etc/lego" run
```

That will generate the certificates under `/etc/lego/certificates/`.

* Configure NGINX

```
mv /opt/bitnami/nginx/conf/bitnami/certs/server.crt /opt/bitnami/nginx/conf/bitnami/certs/server.crt.old
mv /opt/bitnami/nginx/conf/bitnami/certs/server.key /opt/bitnami/nginx/conf/bitnami/certs/server.key.old
ln -s /etc/lego/certificates/DOMAIN.key /opt/bitnami/nginx/conf/bitnami/certs/server.crt
ln -s /etc/lego/certificates/DOMAIN.crt /opt/bitnami/nginx/conf/bitnami/certs/server.key
```

* Restart NGINX

```
nami restart nginx
```

**Comment by HeadBanging** [comment]
That's really great - thank you for your help.  I'm trying them now - but how do I generate certificates for multiple domains?  From the look of it, I can only do one domain here (because it has to be called server.crt).
And since Lets Encrypt certs have to be renewed every six months, how do I handle that?  DO I just have to run lego again as follows:
```
lego --email="EMAIL-ADDRESS" --domains="DOMAIN" --path="/etc/lego" run
```
Presumably I'd also have to run through these steps again from scratch each time the container gets updated?

**Comment by juan131** [comment]
> In either event, I get the same error:

It seems that you're trying to configure the certificate for a domain that is not associated to your IP. Please note that the domain you indicate must be belong to your server. Otherwise, the client won't be able to generate the certificate.

> The next questions is how do I generate certificates for multiple domains?

It's very simple, just run:

```
lego --email="EMAIL-ADDRESS" --domains="DOMAIN-A"  --domains="DOMAIN-B"  --domains="DOMAIN-C" --path="/etc/lego" run
```

You can indicate as many times as you want the parameter `--domains`

> Presumably I'd also have to run through these steps again from scratch each time the container gets updated?

You can persist the certificate so you just have to renew the certificates whenever they expired.

**Comment by HeadBanging** [comment]
> It seems that you're trying to configure the certificate for a domain that is not associated to your IP. Please note that the domain you indicate must be belong to your server. Otherwise, the client won't be able to generate the certificate.

Not so - and if it was so then I wouldn't be able to visit my site by using the domain name rather than the IP address.  I did wonder whether this is an issue with getting a certificate from within a container since the container will have a different IP address to the host machine.  The IP address of the host machine is correctly shown within the error message.

My docker-compose.yml is as follows, in case that's relevant to the investigation:

```
version: '2'

networks:
  app-tier:
    driver: bridge

services:
  nginx:
    image: 'bitnami/nginx:latest'
    depends_on:
        - phpfpm
    networks:
        - app-tier
    ports:
      - '8080:8080'
      - '80:8080'
      - '443:8443'
    volumes:
      - ./nginx/nginx.conf:/bitnami/nginx/conf/nginx.conf
      - ./nginx/fastcgi.conf:/bitnami/nginx/conf/fastcgi.conf
      - ./logs:/opt/bitnami/nginx/logs
      - ./nginx/vhosts:/bitnami/nginx/conf/vhosts
      - ./public/htdocs:/opt/bitnami/nginx/html
      - ./certificates:/bitnami/nginx/conf/bitnami/certs
  phpfpm:
    image: 'bitnami/php-fpm:latest'
    networks:
      - app-tier
    volumes:
      - ./public/htdocs:/app
      - ./logs/php:/opt/bitnami/php/log
```

The host file for my website is as follows:

```
server {
        listen 0.0.0.0:8080;
        server_name  www.<mywebsite>.com;
        server_tokens off;
 
        error_log "/opt/bitnami/nginx/logs/<mywebsite>-error.log";
        access_log  "/opt/bitnami/nginx/logs/<mywebsite>-access.log";

        location / {
                try_files $uri $uri/index.php;
        }

        location ~ \.php$ {
        # fastcgi_pass [PHP_FPM_LINK_NAME]:9000;
                fastcgi_pass phpfpm:9000;
                fastcgi_index index.php;
                include fastcgi.conf;
                root /app;
        }

        location ~ \.htm$ {
                root   /opt/bitnami/nginx/html;
        }
 
        location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
                expires max;
                log_not_found off;
                root   /opt/bitnami/nginx/html;
        }
}
```

**Comment by juan131** [comment]
I think the problem is the same as the one described on this Let's Encrypt Forum thread:

https://community.letsencrypt.org/t/404-on-well-known-acme-challenge/15565/12

You need to add a location for `.well-known` and "allow all".

```
    location ~ /.well-known {
            root   /opt/bitnami/nginx/html;
            allow all;
    }
```

**Comment by HeadBanging** [comment]
Hmm. Sadly, that still doesn't work (scratches head! - Very puzzled).  My server block now looks as follows:
```
server {
        listen 0.0.0.0:8080;
        server_name  www.<mywebsite>.com;
        server_tokens off;
 
        error_log "/opt/bitnami/nginx/logs/<mywebsite>-error.log";
        access_log  "/opt/bitnami/nginx/logs/<mywebsite>-access.log";

        location / {
                try_files $uri $uri/index.php;
        }

        location ~ \.php$ {
        # fastcgi_pass [PHP_FPM_LINK_NAME]:9000;
                fastcgi_pass phpfpm:9000;
                fastcgi_index index.php;
                include fastcgi.conf;
                root /app;
        }

        location ~ \.htm$ {
                root   /opt/bitnami/nginx/html;
        }
 
        location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
                expires max;
                log_not_found off;
                root   /opt/bitnami/nginx/html;
        }

        location ~ /.well-known {
                root   /opt/bitnami/nginx/html;
                allow all;
        }
}
```
I've also tried creating the intermediate directories and setting privileges to 755 - That didn't help either though.  My thinking was that by creating the intermediate directories perhaps that would provide somewhere, with the correct settings, for the test files to be placed.

**Comment by juan131** [comment]
Hi @HeadBanging 

It might a problem with the location directive. Could you try using the location below instead?

```
location ~ /\.well-known/acme-challenge
```

**Comment by HeadBanging** [comment]
Okay, so my server file now looks like this:

server {
        listen 0.0.0.0:8080;
        server_name  www.<mywebsite>.com;
        server_tokens off;
 
        error_log "/opt/bitnami/nginx/logs/<mywebsite>-error.log";
        access_log  "/opt/bitnami/nginx/logs/<mywebsite>-access.log";

        location / {
                try_files $uri $uri/index.php;
        }

        location ~ \.php$ {
        # fastcgi_pass [PHP_FPM_LINK_NAME]:9000;
                fastcgi_pass phpfpm:9000;
                fastcgi_index index.php;
                include fastcgi.conf;
                root /app;
        }

        location ~ \.htm$ {
                root   /opt/bitnami/nginx/html;
        }
 
        location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
                expires max;
                log_not_found off;
                root   /opt/bitnami/nginx/html;
        }

        location ~ /\.well-known/acme-challenge {
                root   /opt/bitnami/nginx/html;
                allow all;
        }
}

But the error is still:
```
2018/03/16 12:14:44 [INFO][www.<mywebsite>.com] acme: Obtaining bundled SAN certificate
2018/03/16 12:14:45 [INFO][www.<mywebsite>.com] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/L6AQtnVFePHEqj_6qtyl1ptlPeqbNd_hs63EM7xiqBw
2018/03/16 12:14:45 [INFO][www.<mywebsite>.com] acme: Could not find solver for: dns-01
2018/03/16 12:14:45 [INFO][www.<mywebsite>.com] acme: Trying to solve HTTP-01
2018/03/16 12:14:49 [www.<mywebsite>.com] Could not obtain certificates
	acme: Error 403 - urn:acme:error:unauthorized - Invalid response from http://www.<mywebsite>.com/.well-known/acme-challenge/kse0FXHgMhhTceta5uhsn1TkO7plZ0ajQVSRFdOqguk: "<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>"
Error Detail:
	Validation for www.<mywebsite>.com:80
	Resolved to:
		134.213.214.###
	Used: 134.213.214.###
```
Note that the Resolved to: and Used: IP addresses are both the same

**Comment by HeadBanging** [comment]
For further reference, I've tried deleting my docker containers and starting again from scratch, using basic simple Bitnami nginx containers and configuration.  The result it exactly the same…

**Comment by juan131** [comment]
I think I now what could be the reason why Let's Encrypt is unable to generate the certificate. 

The client (lego) is starting a standalone server on the port 80. Then, it tries to access to the domain using that port BUT since you have the association below in the `docker-compose.yaml`:

```
    ports:
      - '8080:8080'
      - '80:8080'
```

When accessing through the port 80 is being redirected to the port 8080 where NGINX is running (instead of the standalone server started by Lego).

Could you try to generate the certificate using the port association below? I just want to discard this as the reason for the issue:

```
    ports:
      - '8080:8080'
      - '80:80'
```

**Comment by juan131** [comment]
> If I try changing 8443 to 443 in both the server configuration and the docker-compose.yml, nginx refuses to start - with error

NGINX is started as non-root user and, therefore, it cannot bind any port < 1000. That's the reason why you found that error. Please use the port 8443 instead.

> This no longer results in a '403 Forbidden' - now I get no padlock, and an error from Safari complaining that it can't establish a secure connection.

Could you please share a screenshot of the error you found and the certificate the server is returning?

> keeping the ssl setting at 8443 results in the following error in my website logs:

Could you please share the server configuration file?

**Comment by HeadBanging** [comment]
Problem solved - I needed to keep my certificate name as it was originally written (no need to overwrite nginx defaults) and declare it in the server block for my site!  Thank you for your help.
